httpcore/_async/connection_pool.py, httpcore/_sync/connection_pool.py, httpcore/_threadlock.py
=> Thread safety around connection state in sync case

httpcore/_async/connection_pool.py, httpcore/_async/http11.py, httpcore/_sync/connection_pool.py, httpcore/_sync/http11.py
A bit more care around when connections move out of the PENDING state.
=> Keep PENDING state during connect

httpcore/__init__.py, httpcore/_async/connection_pool.py, httpcore/_async/http11.py, httpcore/_async/http_proxy.py, httpcore/_backends/asyncio.py, httpcore/_backends/base.py, httpcore/_backends/sync.py, httpcore/_backends/trio.py, httpcore/_exceptions.py, httpcore/_sync/connection_pool.py, httpcore/_sync/http11.py, httpcore/_sync/http_proxy.py
=> Proxy support

httpcore/_async/base.py, httpcore/_async/connection_pool.py, httpcore/_async/http11.py, httpcore/_async/http2.py, httpcore/_backends/asyncio.py, httpcore/_backends/auto.py, httpcore/_backends/base.py, httpcore/_backends/sync.py, httpcore/_backends/trio.py, httpcore/_sync/base.py, httpcore/_sync/connection_pool.py, httpcore/_sync/http11.py, httpcore/_sync/http2.py
Added basic pass at `http2=[True|False]` to `AsyncConnectionPool` and `SyncConnectionPool`.
=> Initial HTTP/2 support

httpcore/_async/base.py, httpcore/_async/connection_pool.py, httpcore/_async/http2.py, httpcore/_exceptions.py, httpcore/_sync/base.py, httpcore/_sync/connection_pool.py, httpcore/_sync/http2.py
Refs https://github.com/encode/httpx/issues/283
=> Handle `NoAvailableStreamIDError` case

httpcore/_async/connection.py, httpcore/_async/connection_pool.py, httpcore/_async/http2.py, httpcore/_sync/connection.py, httpcore/_sync/connection_pool.py, httpcore/_sync/http2.py
Refs https://github.com/encode/httpx/issues/514
=> Shared connection acquiry for HTTP/2

httpcore/_async/http_proxy.py
=> Fixed coroutine never awaited in http proxy

httpcore/_async/base.py, httpcore/_async/connection.py, httpcore/_async/connection_pool.py, httpcore/_async/http11.py, httpcore/_async/http2.py, httpcore/_backends/sync.py, httpcore/_sync/base.py, httpcore/_sync/connection.py, httpcore/_sync/connection_pool.py, httpcore/_sync/http11.py, httpcore/_sync/http2.py, httpcore/_threadlock.py, httpcore/_types.py, requirements.txt, setup.cfg
Fix some typing and linting errors as a result.
=> Bring dev tools up to par with httpx

CHANGELOG.md, httpcore/__init__.py
- Fixed tunnel proxy support.
- New `TimeoutException` base class.
=> Version 0.8.0

.github/workflows/publish.yml, .github/workflows/test-suite.yml, requirements.txt, scripts/build, scripts/publish
Adds a package & docs build step, that is *also* included by the Test Suite.
=> Add build step

CHANGELOG.md, httpcore/_async/http_proxy.py, httpcore/_sync/http_proxy.py, tests/async_tests/test_interfaces.py, tests/conftest.py, tests/sync_tests/test_interfaces.py
Fixes https://github.com/encode/httpx/issues/873
=> Pass http2 flag to connections in proxy

README.md, docs/index.md
Closes https://github.com/encode/httpcore/issues/64
=> Add badges to README

httpcore/_async/http11.py, httpcore/_sync/http11.py
Logs all events as exceptions.
=> Remove incorrect debug log

scripts/coverage, scripts/test, setup.cfg
Bring scripts to par with httpx.
Related to https://github.com/encode/httpcore/issues/13.
=> Enforce not decreasing test coverage

httpcore/_async/connection.py, httpcore/_async/connection_pool.py, httpcore/_sync/connection.py, httpcore/_sync/connection_pool.py, httpcore/_utils.py
Forcibly close any erronously hanging connections when the connection pool is closed.
=> Close outstanding connections

httpcore/_async/connection.py, httpcore/_async/connection_pool.py, httpcore/_async/http11.py, httpcore/_async/http2.py, httpcore/_sync/connection.py, httpcore/_sync/connection_pool.py, httpcore/_sync/http11.py, httpcore/_sync/http2.py, tests/conftest.py
To help debug issues like https://github.com/encode/httpcore/issues/44
=> Add trace logs to get_connection_from_pool

scripts/lint
Prompted by https://github.com/encode/httpcore/pull/114#issuecomment-655509240
A note to my future self that might be useful for other contributors. 😄
=> Add comment about why unasync is run after code formatters

httpcore/_async/base.py, httpcore/_sync/base.py
Refs #10. Looks like this when rendered as documentation:
=> Added timeout documentation, refs #10

httpcore/__init__.py, httpcore/_async/connection_pool.py, httpcore/_async/http11.py, httpcore/_async/http2.py, httpcore/_bytestreams.py, httpcore/_sync/connection_pool.py, httpcore/_sync/http11.py, httpcore/_sync/http2.py
Hasn't been run for a while it seems, and `scripts/check` doesn't check for black or isort so we wouldn't have known…
Will submit a follow-up PR to add `black --check` and `isort --check`.
=> Run scripts/lint

httpcore/_async/http_proxy.py, httpcore/_sync/http_proxy.py
Fixes https://github.com/encode/httpx/issues/1169
Before:
After the fix:
=> Always include the port on CONNECT request

setup.cfg
Prompted by https://github.com/encode/httpcore/pull/160#discussion_r470714964
=> Allow untyped test functions

httpcore/_async/http11.py, httpcore/_async/http2.py, httpcore/_async/http_proxy.py, httpcore/_backends/asyncio.py, httpcore/_backends/sync.py, httpcore/_backends/trio.py, httpcore/_sync/http11.py, httpcore/_sync/http2.py, httpcore/_sync/http_proxy.py, requirements.txt, tests/async_tests/test_interfaces.py, tests/sync_tests/test_interfaces.py
Mirroring https://github.com/encode/httpx/pull/1229
Quick fix to un-break CI.
=> Use and pin black 20

README.md, docs/index.md
=> Mention curio in supported async backends

CHANGELOG.md
Cleanup for #231, 0.12.1 has just been pushed to PyPI.
=> Fix 0.12.1 release date

httpcore/_async/http2.py, httpcore/_sync/http2.py
=> Allow Host to override :authority in HTTP2

CHANGELOG.md, httpcore/__init__.py, httpcore/_async/http11.py, httpcore/_sync/http11.py
- Improve error message for specific case of `RemoteProtocolError` where server disconnects without sending a response. (Pull #313)
=> Version 0.13.2

scripts/publish
To resolve this... https://github.com/encode/httpcore/pull/285#issuecomment-829218684
=> Force push docs on publish

README.md
=> Add missing comma to code example

httpcore/_backends/anyio.py, httpcore/_backends/auto.py, requirements.txt, setup.py
=> Use AnyIO by default on asyncio

httpcore/_async/connection.py, httpcore/_async/http2.py, httpcore/_sync/connection.py, httpcore/_sync/http2.py
Tidy up the public/private namespacing on the connection classes.
=> Move attributes on connection classes into private namespace.

httpcore/_backends/anyio.py
=> Fix anyio EOF behaviour on 'read'

CHANGELOG.md, httpcore/__init__.py
- Resolved niggles with AnyIO EOF behaviours. (Pull #358, #362)
=> Version 0.13.5

README.md
Available since 0.14.5, through the `socksio` package.
=> Add SOCKS support to README

.github/stale.yml
Setup [the 'stale' bot](https://github.com/apps/stale) to auto-close issues and PRs.
Let's just start this out on `httpcore` to begin with.
Once we're happy with it we can extend it to `httpx`, and after that consider rolling it out across the whole org.
=> Configure 'stale' bot

setup.py
AnyIO 4.0 is still not released. Just preparing it.
EDIT: Actually, this can already be merged...
=> Bump anyio range to <5.0

httpcore/_ssl.py, httpcore/backends/trio.py, setup.cfg
=> Enable mypy option `--warn-unused-ignores`

CHANGELOG.md, httpcore/__init__.py
- Fix HTTP/1.1 interim informational responses, such as "100 Continue". (#605)
=> Version 0.16.1

httpcore/backends/sync.py
Should we add a test that only runs on Windows and add windows to CI?
Closes: #617
=> Check system when connecting to UNIX socket

httpcore/_async/http_proxy.py, httpcore/_sync/http_proxy.py, tests/_async/test_http_proxy.py, tests/_sync/test_http_proxy.py
Closes https://github.com/encode/httpx/issues/2488
=> Forwarding HTTP proxies should use a fresh connection for every remote host

CHANGELOG.md, httpcore/__init__.py
- Add `socket_options` argument to `ConnectionPool` and `HTTProxy` classes. (#668)
- Improve logging with per-module logger names. (#690)
- Add `sni_hostname` request extension. (#696)
- Resolve race condition during import of `anyio` package. (#692)
- Enable TCP_NODELAY for all synchronous sockets. (#651)
=> Version 0.17.2

docs/extensions.md
Closes #693
Source...
https://github.com/encode/httpcore/blob/1fc34892afe9b599ea2541b1714f616934df9cdd/httpcore/_async/http2.py#L130-L135
=> Add 'stream_id' to extensions documentation.

httpcore/_async/http2.py, httpcore/_sync/http2.py
=> Add 'network_stream' extension to HTTP/2 connections.

.github/ISSUE_TEMPLATE/1-issue.md, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md
=> Add issue and pr templates

CHANGELOG.md, httpcore/_models.py
=> Change type of Extensions

pyproject.toml
Closes #798
Examples
https://github.com/pallets/flask/blob/8037487165a196015a646de25cbce6d0351c8fc4/pyproject.toml#L58
https://github.com/encode/django-rest-framework/blob/4bbfa8d4556b5847e91ba95f457cc862b7a0f027/MANIFEST.in#L3
=> Include tests in the final sdist

CHANGELOG.md
=> Add release date for 1.0.0

CHANGELOG.md
=> typo in changelog

CHANGELOG.md, httpcore/__init__.py
- Fix `float("inf")` timeouts in `Event.wait` function. (#846)
=> Version 1.0.2

httpcore/_async/http2.py, httpcore/_sync/http2.py, pyproject.toml, requirements.txt, scripts/check, tests/concurrency.py
=> Fix Ruff v0.3.0 violations

httpcore/_api.py, httpcore/_async/connection.py, httpcore/_async/connection_pool.py, httpcore/_async/http11.py, httpcore/_async/http2.py, httpcore/_async/http_proxy.py, httpcore/_async/interfaces.py, httpcore/_async/socks_proxy.py, httpcore/_backends/anyio.py, httpcore/_backends/auto.py, httpcore/_backends/base.py, httpcore/_backends/mock.py, httpcore/_backends/sync.py, httpcore/_backends/trio.py, httpcore/_models.py, httpcore/_sync/connection.py, httpcore/_sync/connection_pool.py, httpcore/_sync/http11.py, httpcore/_sync/http2.py, httpcore/_sync/http_proxy.py, httpcore/_sync/interfaces.py, httpcore/_sync/socks_proxy.py, httpcore/_synchronization.py, httpcore/_trace.py, httpcore/_utils.py
Switch to new typing style, close #962.
=> Use new typing style

httpcore/_api.py, httpcore/_async/connection.py, httpcore/_async/connection_pool.py, httpcore/_async/http11.py, httpcore/_async/http2.py, httpcore/_async/http_proxy.py, httpcore/_async/interfaces.py, httpcore/_async/socks_proxy.py, httpcore/_backends/anyio.py, httpcore/_backends/auto.py, httpcore/_backends/mock.py, httpcore/_backends/sync.py, httpcore/_backends/trio.py, httpcore/_exceptions.py, httpcore/_models.py, httpcore/_sync/connection.py, httpcore/_sync/connection_pool.py, httpcore/_sync/http11.py, httpcore/_sync/http2.py, httpcore/_sync/http_proxy.py, httpcore/_sync/interfaces.py, httpcore/_sync/socks_proxy.py, httpcore/_synchronization.py, httpcore/_trace.py
=> Consistent import style

httpcore/_synchronization.py, pyproject.toml
=> Revert "Use AnyIO with `fast_acquire` synchronization "

CHANGELOG.md, httpcore/__init__.py
Bump version to 1.0.8, following the pattern of https://github.com/encode/httpcore/pull/977.
- Fix `AttributeError` when importing on Python 3.14. (#1005)
=> Version 1.0.8
