httpcore/_async/dispatch.py
httpcore/_sync/dispatch.py
mkdocs.yml

* Timeouts as `Dict[str, Optional[float]]`.
* Tweak docstring style.
I've used `Optional[float]` here. We could have just used `float`, and mandate that any missing key should be treated as `None`, but:
1. That's a bit awkward for user-code to build up the dict, given a config model.
2. It's nicer if we can have `None` as an explicit "Off". (Eg. allows us to provide non-off defaults if we want to.)

Timeout as dict

---

httpcore/_async/connection_pool.py
httpcore/_async/http11.py
httpcore/_backends/auto.py
httpcore/_exceptions.py
httpcore/_sync/connection_pool.py
httpcore/_sync/http11.py

A little bit of tidying up.
To follow up on this we might want to make all attributes private on `AsyncHTTP11Connection`, except for `.state` and `.origin`.

Add `ConnectionState.CLOSED`

---

httpcore/_async/connection_pool.py
httpcore/_async/http11.py
httpcore/_sync/connection_pool.py
httpcore/_sync/http11.py

Changes the mechanism by which `stream.close()` ends up either closing connections or releasing them back to the pool.
The change is more code, but it simplifies the flow of execution, since there's no longer any call back from the connection to the connection pool.
Instead we make sure that the connection pool wraps up the returned stream object in a class that calls into `AsyncConnectionPool._request_closed` when the client releases the stream.

Drop request_finished on http connections

---

httpcore/_async/base.py
httpcore/_async/connection_pool.py
httpcore/_async/http11.py
httpcore/_async/http2.py
httpcore/_async/http_proxy.py
httpcore/_backends/asyncio.py
httpcore/_backends/base.py
httpcore/_backends/trio.py
tests/async_tests/test_interfaces.py
unasync.py

PR to solve #9
- Updated `async close` methods to `async aclose`
- Updated `unasync.py` to map `aclose` -> `close`
- Updates async tests

Async close rename

---

requirements.txt
tests/async_tests/test_interfaces.py
tests/conftest.py
tests/sync_tests/test_interfaces.py

Towards #42 
In [socksio](https://github.com/sethmlarson/socksio/) we use [Dante](https://www.inet.no/dante/) to spin up SOCKS 4 and 5 proxies for acceptance tests in Docker but I tend to use [mitmproxy](https://mitmproxy.org/) for debugging proxy issues, since it's written in Python I thought it might be a simple non-docker solution to run it as a thread in the background.
This is a POC only, but it show how we could go about doing that. The tunnel test is failing at an assertion in the connection, not quite sure why but the forwarding ones work well.

Use mitmproxy as a fixture for proxy tests

---

tests/async_tests/test_interfaces.py
tests/sync_tests/test_interfaces.py

For some reason TUNNEL_ONLY was failing for me while working on https://github.com/encode/httpcore/pull/48, but it seems to work fine now, probably missed something.

Add TUNNEL_ONLY to http_proxy test parametrization

---

httpcore/_async/connection.py
httpcore/_async/http11.py
httpcore/_async/http_proxy.py
httpcore/_backends/asyncio.py
httpcore/_sync/connection.py
httpcore/_sync/http11.py
httpcore/_sync/http_proxy.py
tests/async_tests/test_interfaces.py
tests/sync_tests/test_interfaces.py

Fixes #54 split from #55 excluding support for tunneling HTTPS requests. Changes:
- First establish an HTTP connection to our proxy since CONNECT is an HTTP method handled by h11.
- Once successful discard the connection but prevent closing the socket.
- Allow passing a socket to the AsyncHTTPConnection and create a new h11 connection to the target.

Fix tunnel proxy: HTTP requests only

---

CHANGELOG.md
httpcore/_async/http_proxy.py
httpcore/_sync/http_proxy.py
requirements.txt
tests/async_tests/test_interfaces.py
tests/conftest.py
tests/sync_tests/test_interfaces.py

This PR extends https://github.com/encode/httpcore/pull/57 adding support for HTTPS.
The bulk of changes are around managing SSL certificates for mitmproxy to use in tests.

Support HTTPS requests on tunnel proxy

---

.github/workflows/publish.yml
.github/workflows/test-suite.yml
scripts/publish

Adds a GitHub Actions based publish workflow, that deploys to PyPI, and pushes the docs when versions are tagged in GitHub.
Some notes on this:
* Anyone with maintainer permissions will be able to roll a release.
* Version tags should follow the "1.2.3" style. I'd probably prefer GitHub's recommendation of using "v1.2.3" for tags, but we've got history across our projects here, and I guess it's *more* worthwhile to stay in line with that.
* Deploys will fail if the tagged version does not match the `__init__.py` version, which is helpful, since it'll enforce that we've issued, approved, and merged a version PR first.
* Since I've enabled the "enforce up to date with master" setting on the repo, I've drop "build on push to master", and instead we *only* do builds against the PRs. Those two …

Publish workflow

---

CHANGELOG.md
httpcore/__init__.py
httpcore/_async/base.py
httpcore/_async/http11.py
httpcore/_async/http2.py
unasync.py

The build for `httpx 0.13.0.dev0` failed mypy checks due to `SyncHTTPTransport` and `AsyncHTTPTransport` having incompatible types on `.iterator`.
The httpx ContentStream implementations inherit from *both* of those two classes.
In order to resolve that, I've ensured that we're using `aiterator`/`iterator` and `aclose_func`/`close_func` for the two different cases.

Version 0.8.1

---

httpcore/_backends/trio.py
requirements.txt
setup.cfg

Using [trio-typing](https://github.com/python-trio/trio-typing)

Enable type checking for Trio

---

CHANGELOG.md
httpcore/_async/http_proxy.py
httpcore/_sync/http_proxy.py
tests/async_tests/test_interfaces.py
tests/sync_tests/test_interfaces.py

Fixes https://github.com/encode/httpx/issues/922
The issue was that we were manually adding the connection to the pool rather than using the `_add_to_pool` method. By doing this we never acquired (or created) the semaphore, so when attempting to close the connection a new one was created and tried to be released, raising the BoundedSemaphore exception.
Interestingly, this didn't show up in our test suite because when `max_connections` is `None` which is the default we use a `NullSemaphore`. I added both `max_connections` and `max_keepalive` to our proxy tests to cover this particular PR, maybe we should add them to all tests?

Fix forward proxy adding connection to pool

---

CHANGELOG.md
httpcore/__init__.py

- Fix connections using proxy forwarding requests not being added to the
connection pool properly. (Pull #70)

Version 0.8.2

---

.github/workflows/test-suite.yml

So I *think* we need to also run our test suite on the final merge to master, not just on the PR itself.
If we're not doing this, then it's not clear to me that the associated badge is going to actually reflect "colour of the last PR that was merged to master". Having said that, it's actually a bit inscrutable to me.
Something that might help thrash this out would be to leave things as they currently are, and issue a PR with *deliberately* failing tests, and find the answer to...
* Does issuing the PR on it's own update the badge colour?
* Does merging the PR update the badge colour?
I realise I've not worded any of this very clearly, but it's actually not as obvious as you might think that the current test suite behaviour we've got is associated with a meaningful badge.

Run test suite on "merge to master" actions.

---

httpcore/_async/http_proxy.py
httpcore/_sync/http_proxy.py
tests/async_tests/test_interfaces.py
tests/sync_tests/test_interfaces.py

Refs https://github.com/encode/httpx/issues/929#issuecomment-624127681
* Add `Host` and `Accept: */*` headers by default on the tunnel CONNECT requests, if they're not already set.
* De-duplicate proxy headers vs request headers on forwarded requests, rather than naively concatenating them.
I think we should probably roll a new version of `httpcore` from this, then issue an `httpx 0.13.dev1`.

Fix up proxy header behaviour

---

httpcore/_async/connection_pool.py
httpcore/_sync/connection_pool.py

Closes #80
I've only addressed this in ConnectionPool.
It's less clear to me what the behaviour should look like for proxies, so let's treat that in a separate issue & PR.

get-or-create-connection should be an atomic operation

---

httpcore/_async/connection.py
httpcore/_async/connection_pool.py
httpcore/_async/http11.py
httpcore/_async/http2.py
httpcore/_async/http_proxy.py
httpcore/_sync/connection.py
httpcore/_sync/connection_pool.py
httpcore/_sync/http11.py
httpcore/_sync/http2.py
httpcore/_sync/http_proxy.py
httpcore/_utils.py

Closes https://github.com/encode/httpcore/issues/58
I tried to replicate the calls we used to have in httpx, may have missed some but we can just add them as needed moving forward.

Add logger trace

---

httpcore/_async/http2.py
httpcore/_backends/asyncio.py
httpcore/_sync/http2.py

Honor max concurrent streams

---

httpcore/_async/http2.py
httpcore/_sync/http2.py

Right, there was some stuff I didn't quite get correct in #89
Absurdly I'd forgotten to use `http2=True` in my testings. This is the script I'm using now for this...
```python
import asyncio
async with httpcore.AsyncConnectionPool(http2=True) as client:
await asyncio.gather(*[request(client, idx) for idx in range(1000)])
async def request(client, idx):
http_version, status_code, reason_phrase, headers, stream = await client.request(
method=b'GET',
url=(b'https', b'example.org', 443, b'/'),
headers=[(b'host', b'example.org:443')]
)
try:
body = b''.join([chunk async for chunk in stream])
finally:
await stream.aclose()
asyncio.run(main())
```
The changes here are:
* We need to use the *local* settings to determine how many concurrent streams *we* can issue, …

Max concurrent stream improvements

---

httpcore/_async/base.py
httpcore/_async/connection.py
httpcore/_async/connection_pool.py
httpcore/_async/http2.py
httpcore/_async/http_proxy.py
httpcore/_sync/base.py
httpcore/_sync/connection.py
httpcore/_sync/connection_pool.py
httpcore/_sync/http2.py
httpcore/_sync/http_proxy.py
httpcore/_types.py
httpcore/_utils.py

* Port in URL becomes optional.
* Origin stays as `Tuple[bytes, bytes, int]`, since we need a canonical form there.
* `proxy_origin` becomes `proxy_url` for better consistency.
HTTPX would need to update the `proxy_origin` form it uses to `proxy_url`.

Port becomes optional

---

CHANGELOG.md
httpcore/__init__.py

I think we can push the 0.9.0 for `httpcore` now, which we'll use with `httpx` 0.13.

Version 0.9.0

---

httpcore/_backends/sync.py

Switch the sync `open_tcp_connection` to use `socket.create_connection`.
This gives us *far* more sensible host resolution, since it will attempt all records, and also means that we've switched sync to IPv4 + IPv6 support.
Really there's more we could do here too... `urllib3` *automatically* determines if IPv6 support is present on the system. https://github.com/urllib3/urllib3/blob/11d68efa7c150823472f0e5309c3a08a1a10c2f2/src/urllib3/util/connection.py#L33-L86
We probably want to do the same, but let's treat that seperately.

Use `socket.create_connection`

---

CHANGELOG.md
httpcore/__init__.py

Related: https://github.com/encode/httpx/pull/1001
- Proper host resolution for sync case, including IPv6 support. (Pull #97)
- Close outstanding connections when connection pool is closed. (Pull #98)

Version 0.9.1

---

README.md
docs/index.md

Tiny fix of example code block in `README.md` and docs.
Noticed this when I used the example code in a test case for `RESPX`.

Fix example code

---

docs/contributing.md
mkdocs.yml
scripts/docs

Closes https://github.com/encode/httpcore/issues/95
Images are shared with HTTPX once https://github.com/encode/httpx/pull/1011 is merged.

Add contributing docs and scripts/docs

---

httpcore/_async/connection.py
httpcore/_async/connection_pool.py
httpcore/_async/http11.py
httpcore/_async/http2.py
httpcore/_sync/connection.py
httpcore/_sync/connection_pool.py
httpcore/_sync/http11.py
httpcore/_sync/http2.py
httpcore/_utils.py
tests/async_tests/test_interfaces.py
tests/conftest.py
tests/sync_tests/test_interfaces.py

Closes https://github.com/encode/httpcore/issues/18

Add connection pool get_connection_stats method

---

requirements.txt
scripts/lint
setup.cfg

Refs https://github.com/encode/httpx/pull/1050
See https://timothycrosley.github.io/isort/CHANGELOG/#500-penny-july-4-2020
Also pins `isort==5.*`.
I reckon the breaking change here in `isort` is going to require action from most projects that depend on it… Starlette, Uvicorn, Databases, Typesystem and others are probably affected too. Will have to issue fixes for my projects as well…

Use isort 5

---

httpcore/_backends/asyncio.py
httpcore/_backends/sync.py
httpcore/_backends/trio.py
tests/conftest.py

Fixes #110, cc @nawarnoori
Now, the test setup detailed in https://github.com/encode/httpcore/issues/110#issuecomment-654891958 results in the following error in all cases:
```console
httpcore._exceptions.ReadError: Server disconnected while attempting read
```

Improve handling of server disconnects

---

README.md
docs/index.md

- The `README.md` example was missing the mandatory `host` header. Used the same as in the docs home example for consistency.
- The `headers` in docs home were using an invalid syntax.

Fix headers in code examples

---

httpcore/_types.py

Fixes a mypy error when `timeout` is defined as a separate variable:
```python
timeout = {"pool": 5.0}
with httpcore.SyncConnectionPool() as http:
_ = http.request(b"GET", (b"https", b"example.com", 443, b"/"), timeout=timeout)
```
```console
debug/test.py:6: error: Argument "timeout" to "request" of "SyncHTTPTransport" has incompatible type "Dict[str, float]"; expected "Optional[Dict[str, Optional[float]]]"
debug/test.py:6: note: "Dict" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
debug/test.py:6: note: Consider using "Mapping" instead, which is covariant in the value type
Found 1 error in 1 file (checked 1 source file)
```
We've seen instances of this several times in the past for HTTPCore and HTTPX, it's a common gotcha…

Tweak TimeoutDict type variance

---

httpcore/_async/http_proxy.py
httpcore/_sync/http_proxy.py

Small internal refactoring to avoid usage of index-based access such as `url[1]` or `response[2]`, hopefully making the HTTP proxy implementation even easier to read. :-)

Improve readability of forward and tunnel implementations

---

tests/async_tests/test_interfaces.py
tests/conftest.py
tests/sync_tests/test_interfaces.py

A quick one - `proxy_server` was using the old `(bytes, bytes, int)` URL form instead of `(bytes, bytes, Optional[int], bytes)`, which was causing mypy errors.
(Related: I think we should also try to get mypy to run on `tests/`, for the same reason than in HTTPX - it helps us catch any usage-related type hints bugs.)

Fix proxy_server fixture URL type

---

httpcore/__init__.py
httpcore/_async/connection_pool.py
httpcore/_exceptions.py
httpcore/_sync/connection_pool.py
tests/async_tests/test_interfaces.py
tests/sync_tests/test_interfaces.py

Closes #124
Once we tie this exception through to `httpx`, this will allow us to drop `enforce_http_url` in `httpx`, and instead defer the decision entirely to the transport layer.
Will later allow us to support mounting transports on schemes other than `http`, `https`.

Add an `UnsupportedProtocol` exception

---

httpcore/_async/base.py
httpcore/_sync/base.py

Nicer base class implementations for `AsyncByteStream` and `SyncByteStream`.
Allows for eg `AsyncByteStream(content=b'...')` usages.
Closes #125

Support eg. `AsyncByteStream(content=b'...')`

---

httpcore/_async/connection.py
httpcore/_async/http.py
httpcore/_async/http11.py
httpcore/_async/http2.py
httpcore/_sync/connection.py
httpcore/_sync/http.py
httpcore/_sync/http11.py
httpcore/_sync/http2.py

For consideration.
We might want to think again about having HTTP/2 be an optional install for our `httpx` 1.0 release onwards.
Done:
* Provide a base HTTP Connection class interface, that is agnostic of HTTP/1.1 and HTTP/2.
* Use the base HTTP Connection class for the `.connection` signature in `AsyncHTTPConnection`.
* Lazily import either `AsyncHTTP11Connection` or `AsyncHTTP2Connection` as required.
To do:
* Import `h2` in `AsyncConnectionPool` if `http2=True` is set, so that we get nice early errors if it is not installed.
* Move `h2` to an optional install, requiring `pip install httpcore[http2]`

Optional HTTP/2

---

httpcore/__init__.py
httpcore/_async/connection_pool.py
httpcore/_async/http11.py
httpcore/_async/http2.py
httpcore/_exceptions.py
httpcore/_sync/connection_pool.py
httpcore/_sync/http11.py
httpcore/_sync/http2.py

Distinguish between local and remote protocol errors, so that we can expose local errors for invalid requests, eg...
```python
>>> import httpcore
>>> http = httpcore.SyncConnectionPool()
>>> http.request(b"GET", (b'https', b'example.org', 443, b'/'))
File "<stdin>", line 1, in <module>
File "/Users/tomchristie/GitHub/encode/httpcore/httpcore/_sync/connection_pool.py", line 153, in request
method, url, headers=headers, stream=stream, timeout=timeout
File "/Users/tomchristie/GitHub/encode/httpcore/httpcore/_sync/connection.py", line 93, in request
return self.connection.request(method, url, headers, stream, timeout)
File "/Users/tomchristie/GitHub/encode/httpcore/httpcore/_sync/http11.py", line 61, in request
self._send_request(method, url, headers, …
```

Add LocalProtocolError, RemoteProtocolError

---

httpcore/_async/http11.py
httpcore/_async/http2.py
httpcore/_sync/http11.py
httpcore/_sync/http2.py

Fixes #135 
Reading the response body in bigger chunks results in a significant performance boost for large bodies, as shown in graphs listed in #135.

Improve performance when receiving large responses

---

README.md
docs/index.md
httpcore/_async/connection_pool.py
httpcore/_sync/connection_pool.py
requirements.txt
setup.py

We'd need to follow up on this with either...
* Making http/2 optional in `httpx` 0.14
* Using `httpcore[http2]` in the `httpx` 0.14 setup.py info.
Of those two I think we should *probably?* push on and make the change with `httpx` 0.14, since it's where we're headed anyway.

Finalize optional HTTP/2

---

docs/api.md
httpcore/__init__.py
httpcore/_async/base.py
httpcore/_async/http11.py
httpcore/_async/http2.py
httpcore/_bytestreams.py
httpcore/_sync/base.py
httpcore/_sync/http11.py
httpcore/_sync/http2.py
unasync.py

This pull request ensures that our `AsyncByteStream` and `SyncByteStream` classes are pure interface classes, without any implementations themselves.
It also introduces the following concrete implementations, which act as helpful classes for developers, so that it's not always strictly necessary to implement a concrete class.
```python
stream = httpcore.PlainByteStream(b"123")
stream = httpcore.IteratorByteStream(iterator=...)  # Optionally, also `close_func=...`.
stream = httpcore.AsyncIteratorByteStream(aiterator=...)  # Optionally, also `aclose_func=...`.
```
Developers don't *need* to use our concrete implementations, as they could instead provide their own implementations, but this change gives us both a nice purity of interface, and the convenience of providing a few very basic …

Pure ByteStream interface

---

httpcore/_async/connection_pool.py
httpcore/_sync/connection_pool.py
tests/async_tests/test_interfaces.py
tests/sync_tests/test_interfaces.py

There are two changes here...
```python
stats = pool.get_connection_info()
```
Instead becomes...
```python
stats = await pool.get_connection_info()
```
This is important because it allows us to run a keep-alive expiry sweep before returning the connection info, so you'll be seeing more valid information.
Secondly, we were previously capping our keep-alive expiry checks to *at most once per second*. Now if `keepalive_expiry` is set, and is *less* than 1.0, then we'll check for expiry more frequently than once per second. In particular this ensures that `keepalive_expiry=0.0` functions as expected.
*Note that `.get_connection_info()` is only introduced from 0.10 onwards, so this is an addition, not a breaking change.*

Tweak `get_connection_info()` and `keepalive_expiry` behaviour.

---

CHANGELOG.md
httpcore/__init__.py

The most notable change in the 0.10.0 release is that HTTP/2 support is now fully optional.
Use either `pip install httpcore` for HTTP/1.1 support only, or `pip install httpcore[http2]` for HTTP/1.1 and HTTP/2 support.
- HTTP/2 support becomes optional. (Pull #121, #130)
- Add `local_address=...` support. (Pull #100, #134)
- Add `PlainByteStream`, `IteratorByteStream`, `AsyncIteratorByteStream`. The `AsyncByteSteam` and `SyncByteStream` classes are now pure interface classes. (#133)
- Add `LocalProtocolError`, `RemoteProtocolError` exceptions. (Pull #129)
- Add `UnsupportedProtocol` exception. (Pull #128)
- Add `.get_connection_info()` method. (Pull #102, #137)
- Add better TRACE logs. (Pull #101)
- `max_keepalive` is deprecated in favour of `max_keepalive_connections`. (Pull #140)
- …

Version 0.10.0

---

CHANGELOG.md
httpcore/__init__.py
httpcore/_async/http_proxy.py
httpcore/_sync/http_proxy.py

- Include `max_keepalive_connections` on `AsyncHTTPProxy`/`SyncHTTPProxy` classes.

Version 0.10.1

---

httpcore/_async/connection_pool.py
httpcore/_sync/connection_pool.py

Noticed that we don't have any helpful info on using `local_address` with wildcards to support IPv4-only or IPv6-only connections.
I *think* I've got all the wording about right here, but would welcome any reviews over it.

Docs on local_address wildcards

---

httpcore/_async/base.py
httpcore/_sync/base.py
httpcore/_types.py

Small user experience improvement :-)
Currently we have this:
```python
with ConcreteTransport() as transport:
reveal_type(transport)  # SyncHTTPTransport
```
This PR allows doing this:
```python
with ConcreteTransport() as transport:
reveal_type(transport)  # ConcreteTransport
```
This helps when accessing transport-specific attributes and methods (such as `.get_connection_info()` on connection pools), both for type checkers and IDEs.

Tweak type hints for transport context managers

---

unasync.py

I am working on Windows, I have to set newline="" to disable universal newlines, which auto converts "\n" to "\r\n" on Windows:
https://docs.python.org/3/library/functions.html#open
> When writing output to the stream, if newline is None, any '\n' characters written are translated to the system default line separator, os.linesep. If newline is '' or '\n', no translation takes place. If newline is any of the other legal values, any '\n' characters written are translated to the given string.
Prompted by:
https://github.com/encode/httpcore/pull/154#discussion_r469231213

Specify newline="" to prevent newline translation on Windows

---

httpcore/__init__.py

I did it as it's done in https://github.com/encode/httpx/pull/1155 (nice idea)

 Set __module__ = "httpcore" for all over the public API

---

httpcore/_async/connection_pool.py
httpcore/_sync/connection_pool.py
tests/async_tests/test_interfaces.py
tests/conftest.py
tests/sync_tests/test_interfaces.py

Our `max_keepalive_connections` config was not actually being passed along correctly, because we were still setting from the deprecated `max_connections` internally.
We need test cases here, but I'd be okay with us resolving this PR and issue a hotfix release without blocking on that, and then make it a priority.

Fix max_keepalive_connections config

---

tests/async_tests/test_interfaces.py
tests/sync_tests/test_interfaces.py

Note: the tests are failing unless the fix mentioned in https://github.com/encode/httpcore/issues/155#issuecomment-673683869 has been merged.

Added new tests for max_keepalive_connections param (AsyncConnectionPool and SyncConnectionPool) (#155)

---

httpcore/_async/http2.py
httpcore/_backends/asyncio.py
httpcore/_backends/sync.py
httpcore/_backends/trio.py
httpcore/_sync/http2.py

Based on #159 but narrowing things down a bit.
Fixes an issue in HTTP/1.1 when the server does not include the `Content-Length` or set `Transfer-Encoding: chunked` but instead uses a server disconnect to signal the end of the response body.
If the server disconnects under HTTP/2 then raise an appropriate error.

Fix server disconnect behaviour.

---

CHANGELOG.md
httpcore/__init__.py

- Added Unix Domain Socket support. (Pull #139)
- Always include the port on proxy CONNECT requests. (Pull #154)
- Fix `max_keepalive_connections` configuration. (Pull #153)
- Fixes behaviour in HTTP/1.1 where server disconnects can be used to signal the end of the response body. (Pull #164)

Version 0.10.2

---

httpcore/_async/connection_pool.py
httpcore/_async/http2.py
httpcore/_backends/asyncio.py
httpcore/_backends/auto.py
httpcore/_backends/base.py
httpcore/_backends/trio.py

In https://github.com/encode/httpcore/pull/169 and #168 you can find pretty the same changes:
`AsyncBackend::time` , `AsyncSemaphore::release` and `AsyncLock::release` have been made async.
I extracted these changes into the separated PR to make the changeset be discussed here.

Making release() and time() async

---

httpcore/_async/connection_pool.py
httpcore/_sync/connection_pool.py

On uvloop, the timer is only accurate to a millisecond. This negatively affects the `test_connection_pool_get_connection_info` test which may fail because the code runs so fast that the check is done on the same millisecond the connections have expired. This should have no practical implications elsewhere.

Allowed expiring connections where idle time == expiration time

---

httpcore/_backends/auto.py
httpcore/_backends/curio.py
requirements.txt
setup.cfg
setup.py
tests/conftest.py
tests/marks/curio.py
unasync.py

I'm trying to implement `curio` backend (closes https://github.com/encode/httpcore/issues/94)
**Warning** : work in progress
What I did:
1. implemented `curio` backend
What I had to change, but **didn't want** (I'm not an `asycn`-guru, I didn't find a way how to clearly invoke a coroutine from the sync context):
1. I made `AsyncLock` and `AsyncSemaphore` release methods async
1. I made `AsyncBackend::time` async
1. I added `pytest.mark.curio` definition to the `conftest.py`

Implement curio backend

---

httpcore/_async/connection.py
httpcore/_async/connection_pool.py
httpcore/_async/http2.py
httpcore/_async/http_proxy.py
httpcore/_backends/base.py
httpcore/_sync/connection.py
httpcore/_sync/connection_pool.py
httpcore/_sync/http.py
httpcore/_sync/http11.py
httpcore/_sync/http2.py
httpcore/_sync/http_proxy.py
tests/async_tests/test_interfaces.py
tests/conftest.py
tests/sync_tests/test_interfaces.py
unasync.py

Add support for `httpcore.AsyncConnectionPool(backend=...)`.
The default behaviour is to use:
* `httpcore.AsyncConnectionPool(backend="auto")`
Which will auto-select an appropriate backend.
The following are also valid...
* `httpcore.AsyncConnectionPool(backend="asyncio")`
* `httpcore.AsyncConnectionPool(backend="trio")`
* `httpcore.AsyncConnectionPool(backend="curio")`
One motivation here is that this PR would allow us to merge a new `AnyIO` backend, without committing ourselves to a switch. We could add `backend="anyio"` in addition to the existing `backend="auto"`.
In the sync case `backend` is currently always just `"sync"`.

Add 'backend=<str>' parameter

---

httpcore/_backends/curio.py

Realized that #175 did not make use of the `local_address` parameter (refs #134).
Relevant part of the curio docs is here: https://curio.readthedocs.io/en/latest/reference.html#open_connection
> _source_addr_ specifies the source address to use on the socket.

Add local_address support for curio

---

.github/dependabot.yml
requirements.txt
scripts/install

Alternative to #162 
This PR pins all entries in our current `requirements.txt`.
Does not include a freeze process, so that we don't have to deal with transitive dependencies cross-platform (see https://github.com/encode/httpcore/pull/162#issuecomment-691639992).
This way this would work is:
* Developers and CI install from `requirements.txt`. Top-level dependencies are pinned, underlying dependencies may change. We assume the pip 2020 resolver will always be able to find transitive dependencies that work. Should work on Linux, macOS, Windows, and any supported Python version.
* Dependabot comes in once a week to check in and update any top-level dev dependencies that need updating.

Pin dependencies in requirements.txt and add Dependabot

---

httpcore/_async/connection_pool.py
httpcore/_sync/connection_pool.py
requirements.txt
tests/async_tests/test_connection_pool.py
tests/sync_tests/test_connection_pool.py
unasync.py

A few basic test cases for `httpcore.AsyncConnectionPool`/`httpcore.SyncConnectionPool` that work at the level of mocking out the underlying connection instances that they use.
Note that unlike `test_interfaces.py` these test cases just run against a single async backend case. Here we're not interested in the different backends, and we're not touching any backend specific code.
These tests aren't perfect but they're a great start towards us being able to test `httpcore` a bit more comprehensively by starting to add some layer-by-layer testing.
We'll also want to use them to help us start to make the contract between `ConnectionPool` and `Connection` more explicit.

Add some basic connection-pool-specific tests

---

httpcore/_async/http2.py

Working with `httpcore` I found that I missed one `await` in https://github.com/encode/httpcore/pull/170
I double checked the rest changes from the https://github.com/encode/httpcore/pull/170, everything apart from this semaphore `release` is ok

Added await to async semaphore release() coroutine

---

CHANGELOG.md
httpcore/__init__.py

- Add await to async semaphore release() coroutine (#197)
- Drop incorrect curio classifier (#192)

Version 0.11.1

---

requirements.txt
scripts/install

It seems dependabot is not using the latest version of pip because it's failing with this error:
```
RequirementsFileParseError('Invalid requirement: --use-feature="2020-resolver"\nrun.py: error: no such option: --use-feature\n')
```
From https://github.com/encode/httpcore/network/updates/63068071

Fix dependabot

---

README.md
docs/index.md

in 0.11.0 the return tuple of `request()` changed: https://github.com/encode/httpcore/blob/master/CHANGELOG.md#0110-september-22nd-2020
examples needed to be adapted to it

Update examples after 0.11.0

---

requirements.txt

I realized after merging https://github.com/encode/httpcore/pull/200 that we have a few outdated dependencies. I've bumped them to avoid getting too many PRs at the same time once dependabot checks this repo.
Here are the changelogs for the libraries:
- [trio](https://trio.readthedocs.io/en/stable/history.html#trio-0-17-0-2020-09-15): a few deprecations but nothing that we use
- [mkdocs-material](https://squidfunk.github.io/mkdocs-material/changelog/#601-_-september-26-2020): some visual changes in the search results
- [anyio](https://anyio.readthedocs.io/en/stable/versionhistory.html): some fixes
- [isort](https://github.com/PyCQA/isort/blob/develop/CHANGELOG.md#554-hotfix-september-29-2020): hotfixes
- [pytest](https://docs.pytest.org/en/stable/changelog.html#pytest-6-1-0-2020-09-26): …

Upgrade all dependencies for dependabot

---

tests/async_tests/test_interfaces.py
tests/conftest.py
tests/sync_tests/test_interfaces.py
tests/utils.py

Attempt at reducing the scope of #194: as a first step, make our tests agnostic to which "live" endpoint we're hitting, by adding a small `Server` class and using it in `test_interfaces.py` (i.e. where we're actually hitting `example.org`).
Next step would be to add Hypercorn, switch `Server`'s properties so that it points to `localhost:<port>`, instead of `example.org`, and use that updated version in fixtures.
Diff size is still not negligible, but hopefully this is a non-controversial and easily reviewable change.

Abstract away example.org in interface tests

---

requirements.txt
tests/async_tests/test_interfaces.py
tests/conftest.py
tests/sync_tests/test_interfaces.py
tests/utils.py

In https://github.com/encode/httpcore/pull/196 comments it was mentioned that the first step of implementing `socks` proxy support might be replacing `mitmproxy` by `pproxy` (which allows us to test `http`, `socks4` and `socks5` support)
So that I rewrote the test fixtures and changed `requirement` file.
The next steps I propose to do after this PR:
1. rebase https://github.com/encode/httpcore/pull/188 draft
1. move on acroding to the comment https://gitter.im/encode/community?at=5f6db8edf41f4105e4d7a9eb

Migrate http proxy tests to pproxy

---

scripts/lint

`flake8` during `script/test` invocation raises an error if we have unused imports.
As `script/lint` already calls `autoflake`, we can add `--remove-all-unused-imports --ignore-init-module-imports` to the call, which might make development process easier

Add remove-all-unused-imports to autoflake invocation

---

httpcore/_backends/asyncio.py

Closes https://github.com/encode/httpx/issues/1213
There is a gist in the issue, which can help you reproduce the error: [link](https://gist.github.com/cdeler/f43704721829e6ed3c799ddc7d443d5c) . You can also switch the async backend and check, that the error appears only when we `asyncio` backend.
The introduced fix mends the error, so that the error message caused by the exception looks like:
> httpcore.RemoteProtocolError: peer closed connection without sending complete message body (received 917504 bytes, expected 1000000)
instead of the original stacktrace from the issue
**There is a problem:**
I cannot figure out how to make a unit test for this error

Treat asyncio `resume_reading` error as a closed connection

---

httpcore/_async/http11.py
httpcore/_sync/http11.py
setup.py

Closes https://github.com/encode/httpx/issues/538
Update `h11` and expose raw HTTP header casing, rather than forced-lowercase.

Preserve HTTP header casing

---

.github/dependabot.yml

As agreed in the comments of https://github.com/encode/httpcore/pull/212, switching to monthly updates to lower the noise.
Docs: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#scheduleinterval

Increase dependabot's schedule interval to monthly

---

requirements.txt
scripts/test
setup.cfg

After https://github.com/encode/uvicorn/pull/809 it would be great to introduce the same changes in `httpcore`
Pros:
1. `pytest-cov` makes work in IDE harder, suppressing breakpoints ([link](https://pytest-cov.readthedocs.io/en/latest/debuggers.html))
1. `pytest-cov` overwrites some `coverage` flags (probably to be compatible with other plugins e.g. `pytest-xdist`)

Replacing pytest-cov by coverage

---

.github/workflows/test-suite.yml

We added the `Python :: 3.9` trove classifier in #215, but forgot to actually add 3.9 to our test matrix. :-)

Add Python 3.9 to test matrix

---

httpcore/_async/connection.py
httpcore/_async/connection_pool.py
httpcore/_backends/anyio.py
httpcore/_backends/asyncio.py
httpcore/_backends/auto.py
httpcore/_backends/base.py
httpcore/_backends/curio.py
httpcore/_backends/sync.py
httpcore/_backends/trio.py
httpcore/_sync/connection.py
httpcore/_sync/connection_pool.py
httpcore/_utils.py
tests/async_tests/test_retries.py
tests/sync_tests/test_retries.py
tests/test_utils.py

Alternative to https://github.com/encode/httpx/pull/1196, prompted by https://github.com/encode/httpx/pull/1196#issuecomment-690148589
Closes https://github.com/encode/httpx/issues/1141
This PR adds off-by-default "retry on connection failure" capability to the connection pool, using a `retries=<int>` option. Also includes an exponential backoff mechanism, with a fixed backoff factor of 0.5 for now (so, 0s, 0.5s, 1.0s, 2.0s, 4.0s, etc).
We add it at the transport layer, as close to opening sockets as possible, so that connect retries don't interact with the connection pooling logic, so that we do "acquire a connection, open a socket, open a socket, …, release the connection".
(We're in a better position now to add this feature now, because we have a `backend` option on the connection pool …

Add connect retries

---

httpcore/_async/connection.py
httpcore/_async/connection_pool.py
httpcore/_async/http.py
httpcore/_async/http11.py
httpcore/_async/http2.py
httpcore/_backends/anyio.py
httpcore/_backends/asyncio.py
httpcore/_backends/base.py
httpcore/_backends/curio.py
httpcore/_backends/sync.py
httpcore/_backends/trio.py
httpcore/_sync/connection.py
httpcore/_sync/connection_pool.py
httpcore/_sync/http.py
httpcore/_sync/http11.py
httpcore/_sync/http2.py
httpcore/_utils.py
tests/async_tests/test_connection_pool.py
tests/async_tests/test_interfaces.py
tests/conftest.py
tests/sync_tests/test_connection_pool.py
tests/sync_tests/test_interfaces.py

Closes #182 
urllib3 had to deal with an issue similar to #182 a while ago: https://github.com/urllib3/urllib3/issues/589
Their approach was to backport a bunch of 3.5+ logic to maintain 2.7 compatibility, but we're lucky enough to be able to use that logic from the stdlib in the form of the [`selectors`](https://docs.python.org/3/library/selectors.html) module, a "higher-level" alternative to `select` that handles cross-platform subtleties among other things.
This PR switches the sync backend to use `selectors.select()` instead of `select.select()` for detecting whether a connection was dropped (i.e. whether the underlying socket has become immediately readable).
Confirmed that this solves #182, since the CI build passes here but fails on #219.

Tweak dropped connection detection

---

httpcore/_backends/anyio.py
httpcore/_backends/curio.py
httpcore/_backends/trio.py
tests/async_tests/test_interfaces.py
tests/sync_tests/test_interfaces.py

Closes #224 
The problem in #224 turns out to hit`trio` / `anyio+trio` for both TCP and UDS.
We were not properly mapping `OSError` in those places, and this PR fixes that, adding regression tests to our test suite to make sure the proper behavior applies everywhere.

Properly wrap OS errors when using trio

---

httpcore/_async/http_proxy.py
httpcore/_sync/http_proxy.py
tests/async_tests/test_interfaces.py
tests/sync_tests/test_interfaces.py
tests/utils.py

Fixes https://github.com/encode/httpx/issues/1360
I extracted a tunnel proxy connection establishing into the separated method, and wrapped it by `try`-`except` statement, closing the `proxy_connection` if it's necessary.
Also I added the unit test and a test fixture from https://github.com/encode/httpx/issues/1360 comments

Fixed the problem with socket, which might leak when tunnel proxy connection couldn't be establish

---

CHANGELOG.md
httpcore/__init__.py

Figured the connect retries addition wasn't warranting a minor bump (HTTPX is pinned to `httpcore==0.12.*`), and there's precedent to that (eg when we added UDS support back), but happy to reconsider.
---
- Add connect retries. (Pull #221)
- Tweak detection of dropped connections, resolving an issue with open files limits on Linux. (Pull #185)
- Avoid leaking connections when establishing an HTTP tunnel to a proxy has failed. (Pull #223)
- Properly wrap OS errors when using `trio`. (Pull #225)

Version 0.12.1

---

requirements.txt
tests/async_tests/test_interfaces.py
tests/conftest.py
tests/sync_tests/test_interfaces.py
tests/utils.py

Re-ignite of #194:
Closes #109 
100% of our tests now run locally (and switching to `pproxy` (via #196) made this possible with much less pain :-)).
Note: Hypercorn only runs on 3.7, so on 3.6 we keep testing against the `example.org` website, like we do currently. There's a bit of overhead to that, but nothing too blocking I hope, and it's actually nice that we keep some coverage against real-world websites.
Follow-ups include:
- Use Hypercorn for the UDS tests as well, so we remove can Uvicorn entirely (instead of keeping both Hypercorn and Uvicorn as this PR does for now, for ease of reviewing).

Introduce Hypercorn as a local test server

---

requirements.txt
tests/async_tests/test_interfaces.py
tests/conftest.py
tests/sync_tests/test_interfaces.py
tests/utils.py

Follow-up to #205
Use `hypercorn` for UDS tests. Had to refactor `HypercornServer` a bit to remove the `host/port` options, and use `bind` in all cases.
We can't ditch `uvicorn` entirely because `hypercorn` is 3.7+ only, so we only install and use `uvicorn` on 3.6.
The great part here is that we now use the `Server` interface across all tests.

Use Hypercorn for UDS tests

---

tests/async_tests/test_retries.py
tests/sync_tests/test_retries.py

Prompted by https://github.com/encode/httpcore/pull/233#issuecomment-723445718
It's _probably_ due to Hypercorn (#205), that may be a tiny bit slower, and so this is most likely affecting master too.

Fix flaky test

---

httpcore/_backends/asyncio.py

Closes https://github.com/encode/httpx/issues/1387
Fixed the problem with `asyncio` backend, when it incorrectly handles connection timeouts.

Properly wrap asyncio connect errors

---

httpcore/_async/connection.py
httpcore/_sync/connection.py
tests/test_threadsafety.py

Fixes https://github.com/encode/httpx/issues/1393
Moves the local import of the HTTP/1.1 connection class to a global one. It wasn't necessary (`h11` is always installed), and it's a non-threadsafe trick which started causing `ImportError` on Python 3.9 (that it worked in 3.8 and before was actually considered as a bug: https://bugs.python.org/issue35943).
Also adds a basic test case to verify that `httpcore.SyncConnectionPool` can indeed be used in thread-concurrent environments.
Local testing showed that this is not a problem for `h2`, so keeping that local import as-is for now.
cc @Senpos

Fix import of HTTP/1.1 connection causing thread-safety bug on 3.9

---

CHANGELOG.md
httpcore/__init__.py

- Properly wrap connect errors on the asyncio backend. (Pull #235)
- Fix `ImportError` occurring on Python 3.9 when using the HTTP/1.1 sync client in a multithreaded context. (Pull #237)

Version 0.12.2

---

httpcore/_async/http2.py
httpcore/_sync/http2.py

Follow up to #241
* Drop pseudo-headers being stripped. Let's treat any behaviour there separately.
* If a Host header is included, then don't auto-append port info onto it.
* Minor tweak of comment.

Follow up tweaks to Host header precedence for :authority in HTTP/2

---

httpcore/_backends/asyncio.py
requirements.txt
tests/backend_tests/test_asyncio.py

transport.get_extra_info('socket') may return None when connection is dropped.
This commit makes sure we expect such case.
Also, that means socket is readable so that the stream user would be notified/awaken and act accordingly.
Fixes https://github.com/encode/httpcore/issues/239

Fix SocketStream.is_readable()

---

httpcore/_backends/anyio.py
tests/async_tests/test_interfaces.py
tests/sync_tests/test_interfaces.py

In https://github.com/encode/httpx/issues/1387#issuecomment-726775441 I found that `anyio` backend has problem with connection timeouts [here](https://github.com/encode/httpcore/blob/db81ed09592bac8ce740b3be74cf99c86a68c104/httpcore/_backends/anyio.py#L170-L186):
```python
exc_map = {
OSError: ConnectError,
TimeoutError: ConnectTimeout,
BrokenResourceError: ConnectError,
}
with map_exceptions(exc_map):
async with anyio.fail_after(connect_timeout):
stream: anyio.abc.ByteStream
stream = await anyio.connect_tcp(
unicode_host, port, local_host=local_address
)
if ssl_context:
stream = await TLSStream.wrap(
stream,
hostname=unicode_host,
ssl_context=ssl_context,
standard_compatible=False,
)
```
As `assert isinstance(TimeoutError(), OSError)`, the above `map_exceptions` throws `ConnectError` in …

Fix connect timeouts for anyio backend

---

httpcore/_backends/asyncio.py

What do we think about this to help users understand what an `is_readable` means for a disconnected socket?

Tweak `is_readable` comment.

---

httpcore/_backends/asyncio.py

Closes https://github.com/encode/httpx/issues/859
Turns out we need to call `protocol.connection_made()`. It calls `stream_reader.set_transport(...)`, as well as a bunch of other stuff, _including_ marking the reader as being "over SSL", which fixes the warning saw in the issue.
See https://github.com/encode/httpx/issues/859#issuecomment-740004212 for the detailed analysis.

Fix asyncio SSL warning when using proxy tunneling

---

CHANGELOG.md
httpcore/__init__.py

We've got a bunch of fixes in `master` ready for a patch release. :-)
Changelog source: https://github.com/encode/httpcore/compare/0.12.2...cf45ea7
- Abort SSL connections on close rather than waiting for remote EOF when using `asyncio`.  (Pull #167)
- Fix exception raised in case of connect timeouts when using the `anyio` backend. (Pull #236)
- Fix `Host` header precedence for `:authority` in HTTP/2. (Pull #241, #243)
- Handle extra edge case when detecting for socket readability when using `asyncio`. (Pull #242, #244)
- Fix `asyncio` SSL warning when using proxy tunneling. (Pull #249)

Version 0.12.3

---

pyproject.toml
scripts/check
scripts/lint

Personally I'm not keen on us having a `pyproject.toml` exclusively for some bits of black configuration. We don't have this on our other projects, and I don't particularly appreciate IDE design choices forcing us into particular tooling conventions.
I'm okay with us having a conversation around this, but also am very strongly in favour of us being able to stick with similar conventions on our projects across `encode`, and striving towards low-config, low-tooling approaches wherever possible. To me this also include narrowing down the number of magical configuration files we have at the top-level.
Also, I needed a PR excuse to have a look at [the latest build failure nonsense](https://github.com/encode/httpcore/runs/1785395873).

Drop pyproject.toml

---

README.md

Headers are defined as a list of `Tuple[bytes, bytes]`, so the user-agent
header in the example needs to be `bytes`.

Fix README to use bytes for user-agent header

---

CHANGELOG.md
httpcore/__init__.py

Draft release: https://github.com/encode/httpcore/releases/tag/untagged-4e4fcbbf7fc89b686063
The 0.13 release updates the core API in order to match the HTTPX Transport API,
introduced in HTTPX 0.18 onwards.
An example of making requests with the new interface is:
```python
with httpcore.SyncConnectionPool() as http:
status_code, headers, stream, extensions = http.handle_request(
method=b'GET',
url=(b'https', b'example.org', 443, b'/'),
headers=[(b'host', b'example.org'), (b'user-agent', b'httpcore')]
stream=httpcore.ByteStream(b''),
extensions={}
)
body = stream.read()
print(status_code, body)
```
- The `.request()` method is now `handle_request()`. (Pull #296)
- The `.arequest()` method is now `.handle_async_request()`. (Pull #296)
- The `headers` argument is no longer optional. (Pull …

Version 0.13.0

---

httpcore/_backends/anyio.py
httpcore/_backends/asyncio.py
httpcore/_backends/sync.py
httpcore/_backends/trio.py

When a connection fails to close gracefully we're currently raising exceptions.
Actually I really don't think we want to be doing that.
An exception raised during connection close means that the connection wasn't terminated gracefully, but it will still be terminated. Raising exceptions here just means that:
* We can have cases where a request/response cycle runs to completion, but the client library will raise an exception because an unclean close occurred.
* We can have cases where an exception occurs on issuing a request against the connection pool, where we tear down an expired keep alive connection before issuing a fresh request, but an exception ends up being raised.
* We're closing a client and an exception is raised, that we really don't want to occur.

Don't raise exceptions on graceless close cases

---

httpcore/_backends/anyio.py
httpcore/_backends/asyncio.py
httpcore/_backends/curio.py
httpcore/_backends/sync.py
httpcore/_utils.py
tests/backend_tests/test_asyncio.py

Refactoring for better resilience.
* More consistent use of `is_socket_readable` from the `_utils.py` module.
* Handles the case where `socket.fileno()` returns `-1`.

More resiliant `is_readable` testing

---

CHANGELOG.md
httpcore/__init__.py

- More resiliant testing for closed connections. (Pull #311)
- Don't raise exceptions on ungraceful connection closes. (Pull #310)

Version 0.13.1

---

httpcore/_async/http11.py
httpcore/_sync/http11.py

Refs: https://github.com/encode/httpx/issues/1478
Currently if the server is in a listening state, then disconnects without sending a response, then users will see the following error...
```python
httpcore.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
```
Which really isn't informative as an end-user. We probably would prefer to special case this particular transition as a `ConnectError`. It's not quite the same as a *network* `ConnectError`, since it occurs in cases where the connection was already established and hanging around, but is closed once it an incoming request is sent.
It's not super obvious if we want to treat this case as a `ConnectError` or something else. Here's our existing hierarchy in this area...
* NetworkError
* …

Raise ConnectError when server disconnects without sending a response

---

httpcore/_async/connection_pool.py
httpcore/_async/http11.py
httpcore/_sync/connection_pool.py
httpcore/_sync/http11.py
scripts/publish
setup.py
tests/async_tests/test_http11.py
tests/sync_tests/test_http11.py

I want to start broadening out our testing. The reliable way for us to really start to dig into all the corners is to use mock backends for the majority of our tests, so that we can exactly specify which bytes are returned, and when sockets should disconnect etc.
Taking a first pass at this with some simple HTTP/1.1 test cases.

Additional HTTP/1.1 tests.

---

httpcore/_async/http2.py
httpcore/_sync/http2.py
tests/async_tests/test_http11.py
tests/async_tests/test_http2.py
tests/sync_tests/test_http11.py
tests/sync_tests/test_http2.py

HTTP/2 tests with MockBackend

---

httpcore/_utils.py

Fixes the case where socket has been monkey-patched by something like eventlet, which removes support for the poll() method.
Resolved #327

Use select.select when select.poll is not available (#327)

---

CHANGELOG.md
httpcore/__init__.py

- Support HTTP/2 prior knowledge, using `httpcore.SyncConnectionPool(http1=False)`. (Pull #333)
- Handle cases where environment does not provide `select.poll` support. (Pull #331)

Version 0.13.3

---

CHANGELOG.md
httpcore/__init__.py

- Improved error messaging when URL scheme is missing, or a non HTTP(S) scheme is used. (Pull ##354)
- Switched to `anyio` as the default backend implementation when running with `asyncio`. Resolves some awkward [TLS timeout issues](https://github.com/encode/httpx/discussions/1511).

Version 0.13.4

---

httpcore/_backends/anyio.py

Use 'standard_compatible=False' for all TLS streams.

---

CHANGELOG.md
httpcore/__init__.py

- Close sockets when read or write timeouts occur. (Pull #365)

Version 0.13.6

---

scripts/install

```
WARNING: --use-feature=2020-resolver no longer has any effect, since it is now the default dependency resolver in pip. This will become an error in pip 21.0.
```

Remove `--use-feature` switch from pip install command

---

CHANGELOG.md
httpcore/__init__.py
httpcore/_async/connection_pool.py
httpcore/_sync/connection_pool.py

The formatting in #354 of the error messages was all wrong. This pull request still retains the neater error messaging, but doesn't mirror back the URL string that was passed. (Since it's actually a little bit awkward to get right.)

Fix invalid scheme errors

---

CHANGELOG.md
httpcore/__init__.py

- Fix broken error messaging when URL scheme is missing, or a non HTTP(S) scheme is used. (Pull #403)

Version 0.13.7

---

CHANGELOG.md
README.md
docs/index.md

Release draft: https://github.com/encode/httpcore/releases/tag/untagged-1e559d0bc081ba647499
---
The 0.14 release is a complete reworking of `httpcore`, comprehensively addressing some underlying issues in the connection pooling, as well as substantially redesigning the API to be more user friendly.
Some of the lower-level API design also makes the components more easily testable in isolation, and the package now has 100% test coverage.
See [discussion #419](https://github.com/encode/httpcore/discussions/419) for a little more background.
There's some other neat bits in there too, such as the "trace" extension, which gives a hook into inspecting the internal events that occur during the request/response cycle. This extension is needed for the HTTPX cli, in order to...
* Log the point at …

Version 0.14

---

httpcore/_async/__init__.py
httpcore/_sync/__init__.py
setup.py

Closes #426
* `certifi` needs to be included in the install dependancies.
* `h2` should be an optional import.

Fix import issues.

---

CHANGELOG.md
httpcore/__init__.py

- `max_connections` becomes optional. (Pull #429)
- `certifi` is now included in the install dependancies. (Pull #428)
- `h2` is now strictly optional. (Pull #428)

Version 0.14.1

---

httpcore/_async/connection.py
httpcore/_sync/connection.py
tests/_async/test_connection_pool.py
tests/_sync/test_connection_pool.py

Connections which fail should not remain in the pool

---

CHANGELOG.md
httpcore/__init__.py

- Failed connections no longer remain in the pool. (Pull #433)

Version 0.14.2

---

httpcore/_async/http2.py
httpcore/_sync/http2.py
tests/_async/test_http2.py
tests/_sync/test_http2.py

This is just a bit of internal refactoring, that isn't actually ever hit in normal operation.
This difference in exception would only be visible is a developer was working with `HTTP2Connection` directly, and attempted to send a request to an incorrect origin. Given that this is just an internal guard-rail bit of defensive programming, it really ought to be a `RuntimeError`. The `ConnectionNotAvailable` special case is used for when we need the connection pool to re-attempt a request.
This changes now matches the exception used in the equivalent HTTP/1.1 case.

Use RuntimeError for HTTP/2 request made to incorrect origin on connection.

---

tests/_async/test_http2.py
tests/_sync/test_http2.py

Fix up some HTTP/2 test cases with `test_http11_*` names. 🤭

Fix misnamed test cases

---

httpcore/_async/connection_pool.py
httpcore/_sync/connection_pool.py

When there's more than one request made (or queued) on a connection, and the connection is closed, we should guard against trying to pop it from the pool twice. There's no good reason to assume that  of the multiple calls to `response_closed()` that only the final call will happen to satisfy `connection.is_closed()`.

Fix race condition when removing closed connections from the pool

---

CHANGELOG.md
httpcore/__init__.py

- Fix race condition when removing closed connections from the pool (#437)

Version 0.14.3

---

httpcore/_async/http2.py
httpcore/_sync/http2.py

While looking at https://github.com/encode/httpx/issues/1414 I've come across a race condition in the HTTP/2 handling. It's not something I'm able to figure out any sensible test case for, but can describe how to reproduce locally...
First we'll setup `Hypercorn` as a locally HTTP/2-capable server...
**app.py**
```python
async def app(scope, receive, send):
if scope["type"] != "http":
raise Exception("Only the HTTP protocol is supported")
await send({
'type': 'http.response.start',
'status': 200,
'headers': [
(b'content-type', b'text/plain'),
(b'content-length', b'5'),
],
})
await send({
'type': 'http.response.body',
'body': b'hello',
})
```
Let's run that lil kiddo...
```shell
$ hypercorn app:app
```
Okey dokes, now let's bump into it with a coupla concurrent HTTP/2 requests. We've not …

Fix HTTP/2 race condition waiting on stream events.

---

httpcore/_async/http2.py
httpcore/_sync/http2.py

Network errors on HTTP/2 need to be handled a bit differently to HTTP/1.1, because there will often be multiple streams being handled on the same connection. Rather than simply raising the exception we should...
* Save the exception.
* Mark the connection as errored, and return `False` for any future `is_available` calls to disallow further requests being queued on the connection.
* Immediately re-raise the exception on any other network calls, so that it applies across all streams.
This closes https://github.com/encode/httpx/issues/1414 - where the observed behaviour was a disconnect, followed by `TooManyStreams` exceptions. Instead of continuing to queue up further requests behind the *one* request that resulted in a disconnect, we instead want to see the disconnect apply to *all* …

Network errors on HTTP/2 should propagate across all streams.

---

httpcore/_async/http2.py
httpcore/_sync/http2.py
tests/_async/test_http2.py
tests/_sync/test_http2.py

Differentiate between stream and connection errors

---

httpcore/_async/http_proxy.py
httpcore/_sync/http_proxy.py

Proxy headers are missing when proxying requests to `http` endpoints.
Closes https://github.com/encode/httpx/issues/1970

Add missing proxy_header to forward proxy case

---

httpcore/_async/connection.py
httpcore/_async/connection_pool.py
httpcore/_async/http_proxy.py
httpcore/_sync/connection.py
httpcore/_sync/connection_pool.py
httpcore/_sync/http_proxy.py

Only create `SSLContext` instances when they're actually required.
Closes #455

Only create SSLContext when required

---

httpcore/_async/http_proxy.py
httpcore/_sync/http_proxy.py
scripts/coverage
tests/_async/test_http_proxy.py
tests/_sync/test_http_proxy.py

Proxy tunnelling should also support HTTP/2
Refs https://github.com/encode/httpx/issues/1992
The `httpx` package will also need an update here... https://github.com/encode/httpx/blob/7b95ddf3999c6a42fd9311e021c7ecf45fc26f82/httpx/_transports/default.py#L141 and ought to pin against a new minor version of httpcore, once we've got this fix out.

Proxy HTTP/2 support

---

requirements.txt
setup.cfg

Prompted by #461, #463.
Packaging changes that cause unnecessary busy work without adding value.
Simplify, simplify, simplify.

Drop trio-typing package

---

httpcore/_ssl.py
requirements.txt

We really don't care about mypy verifying for us that `certifi.where()` returns a `str`.
It's not worth the package download of `types-certifi` on every CI run.
Somewhat minded to use `mypy --ignore-missing-imports`, which would also allow us to drop that type-stub package. We use `mypy` and type checking throughout our package in order to ensure internal consistency. It's a form of test suite, and allows us to much more safely undertake changes and refactoring when needed. I don't care half as much about what type signatures packages we rely on advertise.
Here's what the `types-certifi` package installs for us: https://github.com/python/typeshed/blob/master/stubs/certifi/certifi.pyi
Related reading: https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports

Drop types-certifi package.

---

requirements.txt

We have several test requirements that are actually no longer being used.
For context, this is a result of the drastic 0.14 re-working, which has made the package much more testable throughout.
We're generally testing against mocked streams, rather than against uvicorn/hypercorn. We have *far* better coverage now than we had before (100%, with only *explicit* exemptions.)
The integration testing we do have is currently using `pytest-httpbin`. Personally I'd like to drop this too in favour of something more explicit, but that's a story for another day.

Drop unused testing requirements

---

requirements.txt

Continuing with the slimming down in #469, #470, #472, #473.
Let's also drop `flake8-bugbear` and `flake8-pie`.
Simplify, simplify, simplify.

Drop extra flake8 checks

---

CHANGELOG.md
httpcore/__init__.py

- Support HTTP/2 on HTTPS tunnelling proxies. (#468)
- Fix proxy headers missing on HTTP forwarding. (#456)
- Only instantiate SSL context if required. (#457)
- More robust HTTP/2 handling. (#253, #439, #440, #441)

Version 0.14.4

---

httpcore/_async/http11.py
httpcore/_sync/http11.py

Revisit #313 - looks like this behaviour got lost in the 0.14 redesign.
Currently if the server is in a listening state, then disconnects without sending a response, then users will see the following error...
```python
httpcore.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
```
Which really isn't informative as an end-user. We probably would prefer to special case this particular transition as a `ConnectError`. It's not quite the same as a *network* `ConnectError`, since it occurs in cases where the connection was already established and hanging around, but is closed once it an incoming request is sent.

Improve 'RemoteProtocolError' message on early server disconnects.

---

httpcore/backends/mock.py
tests/_async/test_connection_pool.py
tests/_sync/test_connection_pool.py

This particular test wasn't quite doing what I'd expected. As a result it was raising errors in the sync case, because of unhandled exceptions that's raised.
The test sends 5 requests to the same domain, against a connection pool that only allows 1 request concurrently.
Each request has to occur strictly in order.
Every 2nd request alternately was failing because the server side was leaving the connection open (No `Connection: close` header), and was only terminating once the request was sent (by responding with a `b""` sentinel marker.)
We fix this by adding a `Connection: close` to the response, so that we've got the expected behaviour. (We could *also* fix this by ensuring that the mock backend returns `is_readable` == True at the point that it is inspected by the connection pool for …

Tidy up warning in test suite

---

httpcore/_async/http_proxy.py
httpcore/_sync/http_proxy.py
tests/_async/test_http_proxy.py
tests/_sync/test_http_proxy.py

This change allows users to specify a `proxy_auth` argument to `HTTPProxy`...
```python
http = httpcore.HTTPProxy(proxy_url=..., proxy_auth=...)
```
Previously any authentication had to be included using the `proxy_headers` argument, and the user was responsible for creating a correctly formed `"Proxy-Authorization"` header.
This addition is prompted by the recent addition of `SOCKSProxy`, which takes a `proxy_auth` argument, and doesn't have any `proxy_headers` argument, because HTTP headers aren't used with socks. Making sure both styles of proxy are aligned here feels more consistent.
We'd also want a generic `proxy_auth` argument rather than a pre-built header if we ever want to be able to support both basic and digest auth styles. (Because we'd want to just be specifying the username …

Add `proxy_auth` argument to `HTTPProxy`

---

CHANGELOG.md
docs/index.md
docs/proxies.md
httpcore/__init__.py

- SOCKS proxy support. (#478)
- Add proxy_auth argument to HTTPProxy (#481)
- Improve error message on 'RemoteProtocolError' exception when server disconnects without sending a response (#479)

Version 0.14.5

---

.github/workflows/publish.yml

Switch the "publish" workflow to run on the "deploy" environment, so that we can require admin-reviews before deploying to PyPI.
I've also:
* Setup a `deploy` environment in this repo's settings.
* Configured it to have "required reviews" from the @encode/operations team (just me right now).
* Created a new PyPI API token for `httpcore`.
* Saved that token in the `deploy` environment's secrets as `PYPI_TOKEN`.
We'll want to push a release so we can check this all runs okay.

Add 'deploy' environment.

---

CHANGELOG.md
httpcore/_async/socks_proxy.py
httpcore/_sync/socks_proxy.py

Closes https://github.com/encode/httpcore/pull/491
The SOCKS proxy code was missing the check for "is this an `https` URL or not" at the point of setting up SSL with the remote endpoint.
Compare this...
https://github.com/encode/httpcore/blob/25a5ad3422b3cd3f0ee8ff02eee755de07393645/httpcore/_async/socks_proxy.py#L241-L257
To the equivalent within a regular connection...
https://github.com/encode/httpcore/blob/25a5ad3422b3cd3f0ee8ff02eee755de07393645/httpcore/_async/connection.py#L135-L151
Bit silly really. Fix is easy-peasy.

Fix SOCKS support for 'http://' URLs

---

CHANGELOG.md
httpcore/__init__.py

- Fix SOCKS support for `http://` URLs. (#492)
- Resolve race condition around exceptions during streaming a response. (#491)

Version 0.14.6

---

CHANGELOG.md
httpcore/_async/socks_proxy.py
httpcore/_sync/socks_proxy.py

Playing with the latest httpcore and httpx versions I noticed an unexpected exception when the connection failed using a SOCKS proxy.
```
httpcore==0.14.6
httpx==0.22.0
```
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Explorer.async_analyze() done, defined at /home/sirius/wapiti/wapitiCore/net/crawler.py:798> exception=AttributeError("'AsyncSocks5Connection' object has no attribute '_connect_failed'")>
File "/home/sirius/wapiti/wapitiCore/net/crawler.py", line 823, in async_analyze
page = await self._crawler.async_send(request)
File "/home/sirius/wapiti/wapitiCore/net/crawler.py", line 592, in async_send
page = await self.async_get(resource, headers=headers, follow_redirects=follow_redirects)
File …
```

Fix variable declaration in AsyncSocks5Connection __init__ method

---

CHANGELOG.md
httpcore/_async/connection_pool.py
httpcore/_sync/connection_pool.py
tests/_async/test_connection_pool.py
tests/_sync/test_connection_pool.py

Since https://github.com/encode/httpcore/pull/491 we've started raising a `RuntimeError` if the connection pool is closed while still handling some requests.
This caused an error in the `httpx` test suite, where a pool timeout was being raised causing the client to close. In this case we *hadn't* removed the request from the connection pool.
This pull request resolves that, as well as resolving the case of task-cancellation-of-a-queued-waiting-request.

Requests which raise a PoolTimeout need to be removed from the pool queue.

---

CHANGELOG.md
httpcore/__init__.py

https://github.com/encode/httpcore/releases/edit/untagged-5bb4ab3a7dc459eb230f
- Requests which raise a PoolTimeout need to be removed from the pool queue. (#502)
- Fix AttributeError that happened when Socks5Connection were terminated. (#501)

Version 0.14.7

---

CHANGELOG.md
httpcore/_async/http_proxy.py
httpcore/_sync/http_proxy.py

Closes https://github.com/encode/httpx/issues/2073
The `CONNECT` request to an HTTP proxy was omitting the request extensions, which meant it had no timeout attached.

Fix proxy CONNECT timeout

---

.github/workflows/test-suite.yml
README.md
docs/index.md
httpcore/_async/interfaces.py
httpcore/_compat.py
httpcore/_sync/interfaces.py
requirements.txt
scripts/check
scripts/lint
setup.cfg
setup.py
unasync.py

Drop Python 3.6

---

CHANGELOG.md
httpcore/__init__.py

- Drop Python 3.6 support (#535)
- Ensure HTTP proxy CONNECT requests include `timeout` configuration. (#506)
- Switch to explicit `typing.Optional` for type hints (#513)
- For `trio` map OSError exceptions to `ConnectError` (#543)

Version 0.15.0

---

.github/stale.yml

See also https://github.com/encode/httpx/pull/2150
---
Bump up the durations on the stalebot to 6 months inactivity.
Wouldn't mind the short durations *except* that stalebot will *repeatedly* attempt to close issues. An alternative would be to configure some exemptions, so that triaged issues don't come up for closing.
https://github.com/probot/stale

Chill-out, @stalebot. ☀️🤖☀️

---

requirements.txt

fixes https://github.com/encode/httpcore/issues/548
the last use of pytest-asyncio was removed in f9b93918a54a49a4e917824ad38cf5bd8da21450

drop redundant pytest-asyncio

---

httpcore/_async/http11.py
httpcore/_sync/http11.py
setup.py

Extends and supersedes #526. 
Updates the types in `_send_event` and `recieve_event` for compatibility with h11 0.14.0.
Tests and `mypy` were run locally on h11 0.13.0 and 0.14.0.
Closes https://github.com/encode/httpcore/pull/503
Closes https://github.com/encode/httpcore/pull/498
Unblocks https://github.com/encode/httpcore/issues/509
h11 0.14.0 includes the upstream fix https://github.com/python-hyper/h11/commit/04cc0f781c47ebfb9f9b188a8e8aa423f276c0b1 allowing us to remove the cast and `isinstance` check from the hot loop which @graingert expressed concerns about in https://github.com/encode/httpcore/pull/526#discussion_r901134892.  A cast is still required for the return value as mypy is not type-narrowing on the `is` clause. We'd probably have to do a weird `isinstance/issubclass` …

Update types for h11 v0.14

---

requirements.txt

See https://github.com/encode/httpcore/pull/583
I've not understood yet *why* importlib-metadata==5.0 breaks the linting for us, or double checked *which* Python version it breaks for, but first step is to get our CI back to clear.

Pin importlib-metadata

---

docs/extensions.md
httpcore/_async/http11.py
httpcore/_sync/http11.py
tests/_async/test_http11.py
tests/_sync/test_http11.py

Prompted by https://github.com/encode/httpcore/discussions/572#discussion-4348090

Support informational responses with HTTP/1.1

---

httpcore/_async/connection_pool.py
httpcore/_sync/connection_pool.py

Closes #564.
I haven't come up with a good test case for this yet, but it resolves the example provided in that issue, by ensuring the request queue modifications happen outside of async context switches.

Fix async cancellation behaviour

---

CHANGELOG.md
httpcore/__init__.py

- Support HTTP/1.1 informational responses. (#581)
- Fix async cancellation behaviour. (#580)
- Support `h11` 0.14. (#579)
---
Currently waiting on #580, #581
Will close https://github.com/encode/httpx/issues/2244

Version 0.16

---

httpcore/_async/http11.py
httpcore/_sync/http11.py
tests/_async/test_http11.py
tests/_sync/test_http11.py

This [discussion on httpx](https://github.com/encode/httpx/discussions/2438) indicates that the latest `httpcore` version has introduced a change in behaviour for "100 Continue" status codes.
This highlights that https://github.com/encode/httpcore/pull/581 has *fixed* our behaviour for "101 Switching Protocols" which is a *final* response code. But *breaks* our behaviour for "100 Continue", "102 Processing", and "103 Early Hints" statues codes, which are all *interim* response codes.
Our behaviour for now ought to treat any `1xx` response codes as interim responses, with the exception of "101 Switching Protocols".
Note that in this PR I've only added tests for 100 and 103, since that's sufficient.
We could feasibly have additional smarts around how we deal with the interim cases. For …

Handle 1xx interim response codes

---

httpcore/backends/sync.py

As discussed in #607, leave `socket.timeout` alone.

Replace use of deprecated `socket.error` > `OSError`

---

setup.cfg
tests/_async/test_connection.py
tests/_async/test_connection_pool.py
tests/_sync/test_connection.py
tests/_sync/test_connection_pool.py
tests/concurrency.py

Enable mypy option `--strict`

---

httpcore/_async/connection_pool.py
httpcore/_sync/connection_pool.py

This reverts pull request #580.
Any accesses to modifying `._pool` or `._requests` should always be guarded by first holding the `._pool_lock`.
Pull request #580 was the wrong approach to resolving https://github.com/encode/httpcore/issues/564.
Closes #613, #615, #621, #624.
Reopens #564 - this is a lower priority bug. I believe I have the correct approach to resolving this, but will follow up with it separately to this pull request.

Revert "Fix async cancellation behaviour"

---

CHANGELOG.md
httpcore/__init__.py

- Revert 'Fix async cancellation behaviour', which introduced race conditions. (#627)
- Raise `RuntimeError` if attempting to us UNIX domain sockets on Windows. (#619)

Version 0.16.2

---

httpcore/_async/connection_pool.py
httpcore/_models.py
httpcore/_sync/connection_pool.py
tests/_async/test_connection_pool.py
tests/_async/test_http11.py
tests/_sync/test_connection_pool.py
tests/_sync/test_http11.py

Allow URLs that use `ws` and `wss` schemes.
Refs https://github.com/encode/httpx/issues/304

Allow `ws` and `wss` schemes.

---

requirements.txt
setup.cfg

The mypy [docs](https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker) says the following about using a global `ignore_missing_imports` option:
> We recommend using this approach only as a last resort: it’s equivalent to adding a # type: ignore to all unresolved imports in your codebase.
This change explicitly states which modules to ignore instead.
Refs #514

Remove global `ignore_missing_imports` mypy option

---

requirements.txt
setup.cfg

Use third party type package for `certify`, `types-certify` from typeshed https://github.com/python/typeshed/tree/main/stubs/certifi.
Refs #618 #514

Use type package for `certifi`

---

httpcore/_async/http2.py
httpcore/_async/http_proxy.py
httpcore/_models.py
httpcore/_sync/http2.py
httpcore/_sync/http_proxy.py

Use generators instead of comprehensions.

Remove unnecessary comprehensions

---

httpcore/_synchronization.py

Closes #626
**example.py**
```python
import trio
async with httpcore.AsyncConnectionPool() as http:
response = await http.request("GET", "https://www.example.com/")
print(response)
trio.run(main)
```
```shell
$ pip install httpcore, trio
$ pip uninstall anyio
$ python example.py
<Response [200]>
```
Turns out this *doesn't* fix the #588 conflict, which is still triggered by the usage of `@pytest.mark.anyio` in the test suite. 🤷‍♂️

Lazy import either 'anyio' or 'trio'

---

httpcore/_async/connection_pool.py
httpcore/_sync/connection_pool.py
httpcore/backends/asyncio.py
httpcore/backends/mock.py
httpcore/backends/trio.py
tests/_async/test_connection_pool.py
tests/_sync/test_connection_pool.py

Closes https://github.com/encode/httpcore/issues/564.
Closes #561 (The motivation given there becomes redundant. Errors will be raised against the connections themselves)
With this script...
**example.py**:
```python
import anyio
async def worker(client, tg):
r = await client.request('HEAD', 'https://google.com')
print(r)
tg.cancel_scope.cancel()  # Cancel our other outstanding requests
async with httpcore.AsyncConnectionPool() as client, anyio.create_task_group() as tg:
for _ in range(3):
tg.start_soon(worker, client, tg)
if __name__ == "__main__":
anyio.run(main)
```
**Before this change...**
```shell
$ venv/bin/python ./example.py 
<Response [301]>
File "./example.py", line 18, in <module>
anyio.run(main)
File …
```

Drop `RuntimeError` on closing a connection pool with active connections.

---

CHANGELOG.md
httpcore/__init__.py

**TODO**:
**Proposed changelog...**
---
- Allow `ws` and `wss` schemes. Allows us to properly support websocket upgrade connections. (#625)
- Forwarding HTTP proxies use a connection-per-remote-host. Required by some proxy implementations. (#637)
- Don't raise `RuntimeError` when closing a connection pool with active connections. Removes some error cases when cancellations are used. (#631)
- Lazy import `anyio`, so that it's no longer a hard dependancy, and isn't imported if unused. (#639)

Version 0.16.3

---

httpcore/_async/socks_proxy.py
httpcore/_sync/socks_proxy.py

Required for https://github.com/encode/httpx/pull/2517
The `SOCKSProxy` and `AsyncSOCKSProxy` classes document a `retries` option but do not accept it.
This adds the parameter and passes it through to the connection pool.

Add `retries` option passthrough to SOCKS proxy classes

---

httpcore/_async/http11.py
httpcore/_sync/http11.py
tests/_async/test_http11.py
tests/_sync/test_http11.py

Increase the default allowable http header size to 100kB similar to curl.
Raised in discussion https://github.com/encode/httpx/discussions/2520

Accept http headers up to 100kB

---

httpcore/_async/http2.py
httpcore/_sync/http2.py
tests/_async/test_http2.py
tests/_sync/test_http2.py
unasync.py

If the remote server sends a settings update for `max_concurrent_streams`, check and potentially update the max number of streams we will use for a connection.
This is related to https://github.com/encode/httpx/discussions/2416.

Adjust max streams when remote settings change

---

httpcore/_async/connection.py
httpcore/_sync/connection.py
tests/_async/test_connection.py
tests/_sync/test_connection.py

Hi,
We are experiencing a small rare issue which has the following trace:
```
File "/usr/local/lib/python3.11/site-packages/anyio/streams/tls.py", line 130, in _call_sslobject_method
result = func(*args)
^^^^^^^^^^^
File "/usr/local/lib/python3.11/ssl.py", line 979, in do_handshake
self._sslobj.do_handshake()
ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:1002)
The above exception was the direct cause of the following exception:
File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
yield
File "/usr/local/lib/python3.11/site-packages/httpcore/backends/asyncio.py", line 78, in start_tls
raise exc
File "/usr/local/lib/python3.11/site-packages/httpcore/backends/asyncio.py", …
```

Retry ConnectError/ConnectTimeout happened in stream.start_tls

---

httpcore/_exceptions.py

Preserves the exception chain instead of displaying "During handling of the above exception, another exception occurred" in the traceback.
Related to https://github.com/encode/httpcore/pull/677

Chain exception re-raise in `map_exceptions`

---

tests/_async/test_http2.py
tests/_sync/test_http2.py

There are a pair of `RstStreamFrame` and `GoAwayFrame` tests here...
* `test_http2_connection_with_rst_stream`
* `test_http2_connection_with_goaway`
...which test a similar flow for both the stream reset and connection goaway cases.
The docstring in the goaway case appears to have been copied incorrectly from the stream reset case.

Fix incorrect docstring in test case

---

httpcore/_async/connection_pool.py
httpcore/_sync/connection_pool.py

Fixs ValueError: list.remove(x): x not in list (#670)
It seemed delete item from self._requests but item not exists.

Fix ValueError: list.remove(x): x not in list (#670)

---

CHANGELOG.md
httpcore/_async/connection_pool.py
httpcore/_sync/connection_pool.py
tests/_async/test_connection_pool.py
tests/_sync/test_connection_pool.py

Second attempt at #681, with tests.
Refs #550 (Possible that it resolves it, unclear?)

Fix pool timeout edge-case.

---

.github/workflows/publish.yml
.github/workflows/test-suite.yml

This PR updates checkout/setup-python GH actions according to these deprecation warnings.
https://github.com/encode/httpcore/actions/runs/5004898315
https://github.com/encode/httpcore/actions/runs/5005203672

Bump GH actions to support Node.js 16

---

CHANGELOG.md
docs/logging.md
httpcore/__init__.py
httpcore/_async/connection.py
httpcore/_async/http11.py
httpcore/_async/http2.py
httpcore/_async/http_proxy.py
httpcore/_async/socks_proxy.py
httpcore/_sync/connection.py
httpcore/_sync/http11.py
httpcore/_sync/http2.py
httpcore/_sync/http_proxy.py
httpcore/_sync/socks_proxy.py
httpcore/_trace.py
tests/_async/test_connection_pool.py
tests/_sync/test_connection_pool.py

This pull request improves our logging behaviour by fanning out different logger names...
*code*:
```python
import logging
logging.basicConfig(
format="%(levelname)s [%(asctime)s] %(name)s - %(message)s",
datefmt="%Y-%m-%d %H:%M:%S",
)
logging.getLogger("httpcore").setLevel(logging.DEBUG)
httpcore.request("GET", "https://www.example.com/")
```
*console*:
```shell
$ venv/bin/python example.py 
DEBUG [2023-05-18 13:01:06] httpcore.connection - connect_tcp.started host='www.example.com' port=443 local_address=None timeout=None
DEBUG [2023-05-18 13:01:06] httpcore.connection - connect_tcp.complete return_value=<httpcore.backends.sync.SyncStream object at 0x10ec1c640>
DEBUG [2023-05-18 13:01:06] httpcore.connection - start_tls.started ssl_context=<ssl.SSLContext object at …
```

Fan out loggers

---

CHANGELOG.md
httpcore/backends/sync.py

The widely documented poor interaction between the Nagle algorithm and TCP's delayed ACK feature, when making short successive writes, leads to unnecessary delays (around 50ms on Linux). This happens in httpcore whenever a POST request is made, since the headers and body are sent as two separate calls.
The TCP_NODELAY can be enabled to disable Nagle's algorithm, and therefore avoid this delay.
The option is already enabled by default for all asyncio and Trio sockets. It is also enabled by CPython's http.client module (which urllib and requests use) and by many high-level HTTP libraries found in other languages, including libcurl, Java's Netty, Rust's reqwest and Go's standard library, to name a few.

Enable TCP_NODELAY for all synchronous sockets.

---

CHANGELOG.md
docs/extensions.md
httpcore/_async/connection.py
httpcore/_sync/connection.py
requirements.txt

Add sni hostname extension

---

CHANGELOG.md
docs/connection-pools.md
httpcore/_async/connection.py
httpcore/_async/connection_pool.py
httpcore/_async/http_proxy.py
httpcore/_sync/connection.py
httpcore/_sync/connection_pool.py
httpcore/_sync/http_proxy.py
httpcore/backends/asyncio.py
httpcore/backends/auto.py
httpcore/backends/base.py
httpcore/backends/mock.py
httpcore/backends/sync.py
httpcore/backends/trio.py
requirements.txt
tests/_async/test_connection.py
tests/_async/test_connection_pool.py
tests/_async/test_http_proxy.py
tests/_sync/test_connection.py
tests/_sync/test_connection_pool.py
tests/_sync/test_http_proxy.py

Add support for socket options

---

tests/_async/test_connection.py
tests/_async/test_connection_pool.py
tests/_async/test_http11.py
tests/_async/test_http2.py
tests/_async/test_http_proxy.py
tests/_async/test_integration.py
tests/_async/test_socks_proxy.py
tests/_sync/test_connection.py
tests/_sync/test_connection_pool.py
tests/_sync/test_http11.py
tests/_sync/test_http2.py
tests/_sync/test_http_proxy.py
tests/_sync/test_integration.py
tests/_sync/test_socks_proxy.py
tests/test_models.py

Clean up our test import style...
* More consistent style.
* Top-level imports make it easier to review that we're testing against public API throughout.

Refactor test import style

---

CHANGELOG.md
httpcore/_trace.py

```python
async def log(a, b):
print(a, b)
httpcore.request("GET", "https://google.com", extensions={"trace": log})
```
```
RuntimeWarning: coroutine 'log' was never awaited
self.trace_extension(prefix_and_name, info)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
```
TypeError: If you are using a synchronous interface, the callback of the `trace` extension should be a normal function instead of an asynchronous function.
```
```python
import trio
def log(a, b):
print(a,b)
async def req():
cl = httpcore.AsyncConnectionPool()
await cl.request("GET", "https://google.com", extensions={"trace": log})
trio.run(req)
```
```
TypeError: object NoneType can't be used in 'await' expression
```
```
TypeError: If you're using an asynchronous interface, …
```

Add exceptions for invalid trace callback

---

httpcore/_async/http2.py
httpcore/_sync/http2.py

* Add missing docstrings in HTTP/2.
* Refactor out `_send_stream_data` and `_send_end_stream`.
I haven't added this to the CHANGELOG because it is a refactoring, not a behavioural change.

Docstrings and minor refactor for HTTP/2.

---

CHANGELOG.md
httpcore/_async/connection_pool.py
httpcore/_async/http11.py
httpcore/_async/http2.py
httpcore/_sync/connection_pool.py
httpcore/_sync/http11.py
httpcore/_sync/http2.py
httpcore/_synchronization.py
tests/test_cancellations.py

Support async cancellations.

---

CHANGELOG.md
httpcore/__init__.py

- The networking backend interface has [been added to the public API](https://www.encode.io/httpcore/network-backends). Some classes which were previously private implementation detail are now part of the top-level public API. (#699)
- Support async cancellations, ensuring that the connection pool is left in a clean state when cancellations occur. (#726)
- Graceful handling of HTTP/2 GoAway frames, with requests being transparently retried on a new connection. (#730)
- Add exceptions when a synchronous `trace callback` is passed to an asynchronous request or an asynchronous `trace callback` is passed to a synchronous request. (#717)

Version 0.17.3

---

httpcore/_async/http11.py
httpcore/_sync/http11.py
tests/_async/test_connection.py
tests/_sync/test_connection.py

Handle cases like HTTP 413, where the request write fails part way through sending, but a properly formed HTTP error response is then sent.
Closes #723
Originally prompted via https://github.com/encode/httpx/discussions/2503

Handle HTTP/1.1 half-closed connections gracefully.

---

.github/workflows/publish.yml
.github/workflows/test-suite.yml
CHANGELOG.md
README.md
docs/index.md
pyproject.toml
scripts/check
scripts/lint

Python 3.7 EOL is approaching, this PR removes its support.
Related to [#2744](https://github.com/encode/httpx/pull/2744).

Drop Python 3.7 support

---

unasync.py

Some patterns became obsolete, but they were not deleted.
I also included a check for unused patterns.

Remove useless patterns from unasync.py

---

CHANGELOG.md
httpcore/__init__.py

- Add support for HTTPS proxies. (#745, # 786)
- Handle `sni_hostname` extension with SOCKS proxy. (#774)
- Change the type of `Extensions` from `Mapping[Str, Any]` to `MutableMapping[Str, Any]`. (#762)
- Handle HTTP/1.1 half-closed connections gracefully. (#641)
- Drop Python 3.7 support. (#727)

Version 0.18.0

---

tests/test_cancellations.py

Now tests randomly fail, which in some places makes development hard (see #756). 
Local testing can randomly fail, and GitHub actions can also fail. 
For example, 3.11 tests fail, causing other actions to be interrupted.
Let's just skip these tests for now and remove the "@pytest.mark.xfail" flag in the pull request, which will resolve #756

Skip the http2 cancellation tests if they fail.

---

requirements.txt

Bump mkdocs-material-extensions from 1.1.1 to 1.2

---

requirements.txt

Bump mkdocs-material-extensions from 1.2 to 1.3

---

CHANGELOG.md
httpcore/_backends/sync.py

Closes #841
I'm not sure how we missed that, but it appears we have an if statement that prevents `TLS-in-TLS` streams for synchronous backends.
@tomchristie included a basic example of how to test this feature in sync and async code in the [pull request that adds HTTPS proxy support](https://github.com/encode/httpcore/pull/786).
This pull request simply corrects `TLS-in-TLS` sync by removing unnecessary if. To test locally, follow the steps outlined in the [PR that adds HTTPS proxy support](https://github.com/encode/httpcore/pull/786).

Fix synchronous TLS-in-TLS streams

---

CHANGELOG.md
httpcore/_async/connection_pool.py
httpcore/_sync/connection_pool.py
httpcore/_synchronization.py

Closes #825.
**example.py**
```python
import asyncio
async with httpcore.AsyncConnectionPool() as pool:
response = await pool.request("GET", "https://www.example.com")
print(response)
asyncio.run(main())
```
**output:**
```shell
$ venv/bin/python ./example.py 
File "/Users/tomchristie/Temp/./example.py", line 11, in <module>
asyncio.run(main())
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
return future.result()
File "/Users/tomchristie/Temp/./example.py", line 6, in main
async with …
```

Raise a neater RuntimeError when the correct async deps are not installed.

---

CHANGELOG.md
httpcore/__init__.py

Provisionally marked up for a release tomorrow...
- Fix pool timeout to account for the total time spent retrying. (#823)
- Raise a neater RuntimeError when the correct async deps are not installed. (#826)
- Add support for synchronous TLS-in-TLS streams. (#840)

Version 1.0.1

---

CHANGELOG.md
httpcore/_synchronization.py

Resolves #845
The issue is that our `AsyncEvent.wait` supports `float('inf')` timeout but `Event.wait` doesn't.
Simple demonstration:
Works
```python
import asyncio
from httpcore._synchronization import AsyncEvent
async def background(event: AsyncEvent):
await asyncio.sleep(2)
event.set()
event = AsyncEvent()
asyncio.create_task(background(event))
await event.wait(timeout=float("inf"))
print('done')
asyncio.run(main())
```
Doesn't work
```python
import threading
import time
from httpcore._synchronization import Event
def background(event: Event):
time.sleep(2) 
event.set()
def main():
event = Event()
threading.Thread(target=background, args=[event]).start()
event.wait(timeout=float("inf"))
print('done')
main()  
```
Error:
```
File …
```

Fix float("inf") timeouts

---

CHANGELOG.md
httpcore/__init__.py
httpcore/_async/socks_proxy.py

If you are using socks proxy, asynchronous client and tracing, it fails with the following error:
```
File "/opt/.../3rdparty_python_httpcore/site-packages/httpcore/_async/socks_proxy.py", line 231, in handle_async_request
with Trace("connect_tcp", logger, request, kwargs) as trace:
File "/opt/.../3rdparty_python_httpcore/site-packages/httpcore/_trace.py", line 50, in __enter__
self.trace(f"{self.name}.started", info)
File "/opt/.../3rdparty_python_httpcore/site-packages/httpcore/_trace.py", line 33, in trace
raise TypeError(
TypeError: If you are using a synchronous interface, the callback of the `trace` extension should be a normal function instead of an asynchronous function.
```

Fix bug with async socks proxy and tracing.

---

httpcore/_models.py
pyproject.toml
requirements.txt
scripts/check
scripts/lint

Refs: https://github.com/encode/httpx/pull/2901

Use ruff format

---

CHANGELOG.md
httpcore/_async/connection.py
httpcore/_async/connection_pool.py
httpcore/_sync/connection.py
httpcore/_sync/connection_pool.py
httpcore/_synchronization.py
requirements.txt
tests/_async/test_connection_pool.py
tests/_sync/test_connection_pool.py

Closes https://github.com/encode/httpcore/issues/830
Closes #785
Closes #861
Closes https://github.com/encode/httpx/issues/1171
Let's talk about what's going on here.
We've got an issue with handling async cancellations correctly, which needs some re-working in order to comprehensively resolve it. We're somewhat in contrast to either `urllib3` (sync) or `aiohttp` (async) here, because we're having to get both the thread-safe and the task-safe-plus-also-support-cancellations cases correct.
Currently we're at thread-safe plus task-safe, but missing correct handling of also allowing external cancellations at any point.
So then...
---
This pull request reworks the handling of the connection pool state. The state is a list of connections, a list of requests, and an association between each …

Safe async cancellations.

---

CHANGELOG.md
httpcore/__init__.py

- Fix support for async cancellations. (#880)
- Fix trace extension when used with socks proxy. (#849)
- Fix SSL context for connections using the "wss" scheme (#869)

Version 1.0.3

---

CHANGELOG.md
httpcore/_backends/anyio.py

Handle `EndOfStream` for anyio backend

---

README.md

We're using level 2 headings everywhere else in this doc.

Consistent headings

---

httpcore/_async/connection_pool.py
httpcore/_sync/connection_pool.py

This PR fixes a typo in the `ConnectionPool` and `AsyncConnectionPool` classes.

Fix typo in `ConnectionPool` and `AsyncConnectionPool`

---

CHANGELOG.md
httpcore/_backends/anyio.py

Handle `SSLError`

---

requirements.txt
scripts/benchmark
tests/benchmark/client.py
tests/benchmark/server.py

Adds benchmarking script comparing `httpcore` against another popular http library `aiohttp`. Related to performance issues `httpcore` has https://github.com/encode/httpx/issues/3215.
This runs 500 requests with 20 requests concurrently. The test is repeated 10 times. Test server has simulated latency of 10ms with 2KB response. Simulating a good network connection (eg in data center conditions).

Add benchmarking script

---

CHANGELOG.md
httpcore/_backends/anyio.py
httpcore/_synchronization.py

Handle `trio` raising `NotImplementedError` on unsupported platforms.

---

httpcore/_models.py
tests/test_models.py

This change is needed to unblock https://github.com/encode/httpx/pull/3178 and support `socks5h` scheme (server-side hostname resolution socks5 proxy). Support for the `socks5h` is needed to ensure global environment variables like `all_proxy="socks5h://..."` can be used reliably with different programs (some of which are httpx based).

default port for the socks5h scheme

---

CHANGELOG.md
httpcore/__init__.py

- Support `proxy=…` configuration on `ConnectionPool()`. (#974)
---
Docs... https://github.com/encode/httpcore/blob/master/docs/proxies.md

Version 1.0.7

---

httpcore/__init__.py

Fixes https://github.com/encode/httpcore/discussions/995.
On Python 3.14, we get an `AttributeError` on import:
```pytb
❯ python3.14
Python 3.14.0a7 (v3.14.0a7:29af6cee02f, Apr  8 2025, 07:53:42) [Clang 16.0.0 (clang-1600.0.26.6)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import httpcore
File "<python-input-0>", line 1, in <module>
File "/private/tmp/httpcore/httpcore/httpcore/__init__.py", line 140, in <module>
setattr(__locals[__name], "__module__", "httpcore")  # noqa
~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'typing.Union' object has no attribute '__module__' and no __dict__ for setting new attributes. Did you mean: '__reduce__'?
```
This is caused by …

Fix `AttributeError` when importing on Python 3.14

---

pyproject.toml

To address the Critical-level CVE:
https://github.com/advisories/GHSA-vqfr-h8mv-ghfj

Update pyproject.toml to avoid h11 dependency security issue

---

CHANGELOG.md
httpcore/__init__.py

- Resolving https://github.com/advisories/GHSA-vqfr-h8mv-ghfj with h11 dependency update. (#1008)

Version 1.0.9
